import type { Lang } from './i18n'

export const dashT = {
  uz: {
    nav: {
      dashboard: 'Dashboard', products: 'Mahsulotlar', orders: 'Buyurtmalar',
      analytics: 'Tahlil', pnl: 'F & Z hisobot', calculator: 'Kalkulyator',
      market: 'Bozor tadqiqoti', settings: 'Sozlamalar', profile: 'Profil', logout: 'Chiqish',
      store: "Do'konim", bozor: 'Bozor', sync: 'Sinxronizatsiya',
      abcxyz: 'ABC-XYZ',
    },
    dashboard: {
      title: 'Dashboard', subtitle: "Xush kelibsiz! Bu sizning do'koningiz analitikasi.",
      badge: "Sizning ma'lumotingiz", sync: 'Sinxronlash',
      all: 'Hammasi', revenue: 'Umumiy daromad', profit: 'Sof foyda',
      orders: 'Buyurtmalar', stock: 'Ombordagi mahsulot',
      recentOrders: "So'nggi buyurtmalar", topProducts: 'Top mahsulotlar',
      viewAll: "Hammasini ko'rish", noData: "Hali ma'lumot yo'q",
      noDataDesc: "Do'koningizni ulash uchun Sozlamalar sahifasiga o'ting, API tokeningizni kiriting va sinxronizatsiyani boshlang. Uzum Market, Yandex Market va Wildberries qo'llab-quvvatlanadi.",
      noDataSynced: "Sinxronizatsiya bajarildi, lekin ma'lumot topilmadi",
      noDataSyncedDesc: "API buyurtma yoki mahsulot qaytarmadi. Yuqoridagi 'Sinxronlash' tugmasini bosib qayta urinib ko'ring.",
      goSettings: "Sozlamalarga o'tish",
      dailyRevenue: 'Kunlik daromad', categories: 'Kategoriyalar',
      product: 'Mahsulot', profit2: 'Foyda', sold: 'Sotilgan',
      syncing: 'Sinxronlanmoqda...', done: 'Tayyor!', err: 'Xato',
      last: "So'nggi", daysSuffix: 'kun',
      yesterday: 'Kecha', thisMonth: 'Bu oy', vsPrev: 'o\'tgan davrga nisbatan',
      customize: 'Moslash', widgetKpis: 'KPI Kartalar', widgetAlerts: 'Ombor ogohlantirishlari', widgetChart: 'Daromad grafigi', widgetCategories: 'Kategoriyalar',
      noProducts: "Mahsulotlar yo'q", noProductsDesc: "Do'koningizni sinxronlang yoki mahsulot qo'shing.",
    },
    export: {
      download: 'Yuklab olish', xlsx: 'Excel (.xlsx)', csv: 'CSV', pdf: 'PDF (chop etish)',
    },
    status: {
      pending: 'Kutilmoqda', confirmed: 'Tasdiqlandi', delivered: 'Yetkazildi',
      cancelled: 'Bekor', returned: 'Qaytarildi',
    },
    products: {
      title: 'Mahsulotlar', count: 'ta mahsulot', empty: "Mahsulotlar yo'q",
      emptyDesc: "Uzum do'koningizni ulab, sinxronizatsiyani boshlang — mahsulotlar avtomatik import qilinadi.",
      goSettings: "Sozlamalarga o'tish",
      all: 'Barchasi', searchPlaceholder: 'Mahsulot nomi, SKU yoki kategoriya...',
      filter: '(filtr)', notFound: 'Hech narsa topilmadi',
      product: 'Mahsulot', category: 'Kategoriya', price: 'Narx', cost: 'Tannarx',
      profit: 'Foyda', margin: 'Margin', sold: 'Sotilgan', stock: 'Ombor',
      exportFilename: 'mahsulotlar',
      colProduct: 'Mahsulot', colSku: 'SKU', colCategory: 'Kategoriya',
      colPrice: "Narx (so'm)", colCost: "Tannarx (so'm)", colProfit: "Foyda (so'm)",
      colMargin: 'Margin (%)', colSold: 'Sotilgan', colStock: 'Ombor',
      filterLowStock: 'Kam qoldi', filterOutOfStock: 'Tugagan',
      filterNoOrders: "Buyurtma yo'q", filterHighMargin: 'Yuqori margin',
      filterHighDrr: 'Yuqori DRR', filterWithAds: 'Reklamali',
      columns: 'Ustunlar', presetDefault: 'Standart', presetCompact: 'Qisqa',
      drr: 'DRR', adSpend: 'Reklama', impressions: "Ko'rsatmalar", clicks: 'Bosishlar', ctr: 'CTR',
      indicators: 'Indikatorlar',
      drrGreen: 'DRR yashil (maks %)', drrYellow: 'DRR sariq (maks %)', drrRedLabel: 'DRR qizil (va undan yuqori)',
      stockYellowLabel: 'Sariq ombor (dona)', stockRedLabel: 'Qizil ombor (dona)',
      indicatorsHint: 'Rang indikatorlari mahsulot jadvaliga qo\'llaniladi',
    },
    orders: {
      title: 'Buyurtmalar', count: 'ta buyurtma', empty: "Buyurtmalar yo'q",
      emptyDesc: "Uzum do'koningizni ulab, sinxronizatsiyani boshlang — buyurtmalar avtomatik import qilinadi.",
      goSettings: "Sozlamalarga o'tish",
      pending: 'Kutilmoqda', confirmed: 'Tasdiqlandi', delivered: 'Yetkazildi',
      cancelledFull: 'Bekor qilindi', returned: 'Qaytarildi',
      all: 'Barchasi', cancelled: 'Bekor',
      searchPlaceholder: 'Buyurtma ID yoki marketplace...', notFound: 'Hech narsa topilmadi',
      orderId: 'Buyurtma ID', marketplace: 'Marketplace', date: 'Sana',
      revenue: 'Daromad', commission: 'Komissiya', delivery: 'Yetkazish',
      items: 'Mahsulotlar', statusCol: 'Holat',
      exportFilename: 'buyurtmalar',
      colDate: 'Sana', colRevenue: "Daromad (so'm)", colCommission: "Komissiya (so'm)",
      colDelivery: "Yetkazish (so'm)",
    },
    analytics: {
      title: 'Kengaytirilgan tahlil', subtitle: 'Sotuv, reklama, qaytarish va vaqt tahlili',
      emptyAfterSync: "Ma'lumotlar sync qilingandan keyin ko'rinadi",
      noShop: "Do'kon ulanmagan",
      noShopDesc: "Sozlamalar sahifasiga o'tib, Uzum API tokeningizni kiriting va sinxronizatsiyani boshlang.",
      goSettings: "Sozlamalarga o'tish",
      freeBannerPre: 'Bepul tarif: faqat oxirgi', freeBannerDays: '7 kun',
      freeBannerPost: "ma'lumoti ko'rsatilmoqda. Ko'proq tarix uchun", freeBannerLink: "Pro ga o'ting",
      daysSuffix: 'kun',
      funnelTitle: 'Sotuv hunisi',
      funnelImpressions: 'Taassurotlar', funnelProductPage: 'Mahsulot sahifasi',
      funnelCart: 'Savat', funnelOrder: 'Buyurtma', funnelProfit: 'Foyda',
      mpData: 'Marketplace ma\'lumoti', marginSuffix: 'marja',
      funnelNote: "* Taassurotlar, sahifa ko'rishlar va savat ma'lumotlari marketplace API orqali qo'shiladi.",
      rankingTitle: 'Mahsulot foydasi reytingi',
      colProductName: 'Mahsulot nomi', colSales: 'Sotuvlar', colRevenue: 'Daromad',
      colCommission: 'Komissiya (~12%)', colProfitUnit: 'Foyda / dona', colProfitability: 'Rentabellik',
      weeklyTitle: 'Haftalik taqqoslash',
      colMetric: "Ko'rsatkich", colThisWeek: 'Bu hafta', colLastWeek: "O'tgan hafta", colDiff: 'Farq',
      mOrders: 'Buyurtmalar', mRevenue: 'Daromad', mProfit: 'Foyda', mReturns: 'Qaytarishlar',
      adTitle: 'Reklama samaradorligi',
      adTotalSpend: 'Jami reklama sarfi (taxm.)', adTotalRevenue: 'Jami daromad', adDrrTotal: 'DRR (jami)',
      colProduct: 'Mahsulot', colAdSpend: 'Reklama xarajati', colDrr: 'DRR %',
      adNoteLabel: 'Eslatma:',
      adNote: "Reklama xarajati hozircha komissiya asosida taxminiy hisoblanmoqda. Real Uzum Ads ma'lumotlari tez orada qo'shiladi.",
      returnsTitle: 'Qaytarishlar tahlili',
      retTotal: 'Jami qaytarishlar', retCount: 'ta', retRate: 'Qaytarish foizi', retValue: 'Qaytarish qiymati',
      retLevel: 'Qaytarish darajasi (ushbu davr)', retAllShops: "Barcha do'konlar",
      retNote: "* Mahsulot bo'yicha qaytarish tahlili uchun buyurtma ↔ mahsulot bog'liqligini API orqali qo'shamiz.",
      priceTitle: 'Narx joylashuvi',
      priceNote: "Raqobatchilar narxi tez orada qo'shiladi — hozircha kategoriya o'rtachasi ko'rsatilmoqda.",
      colYourPrice: 'Sizning narxingiz', colCatAvg: "Kategoriya o'rtachasi", colDiff2: 'Farq %',
      legendBelow: "O'rtachadan past (−10%)", legendAround: "O'rtacha atrofida", legendAbove: "O'rtachadan yuqori (+20%)",
      timeTitle: 'Eng yaxshi sotuv vaqti',
      byDay: "Hafta kunlari bo'yicha", byHour: "Soat bo'yicha",
      days: ['Yakshanba', 'Dushanba', 'Seshanba', 'Chorshanba', 'Payshanba', 'Juma', 'Shanba'],
    },
    pnl: {
      title: 'Foyda va zarar hisoboti',
      subtitleEmpty: "Do'kon sinxronlashtirilgandan so'ng ma'lumotlar ko'rinadi",
      subtitle: "So'nggi 6 oy · Daromad, komissiya va yetkazib berish xarajatlari",
      empty: "Ma'lumot yo'q",
      emptyDesc: "Hisobotni ko'rish uchun avval Uzum do'koningizni ulab, sinxronizatsiyani bajaring.",
      goSettings: "Sozlamalarga o'tish",
      totalRevenue: 'Jami daromad', commission: 'Komissiya', delivery: 'Yetkazib berish',
      netNoComm: 'Sof (komissiyasiz)',
      cogsNote: "Tannarx (COGS) hisob-kitobga kiritilmagan — bu ustunni qo'shish uchun mahsulot sotib olish narxlarini sozlamalarda yangilang. Sof ko'rsatkich = daromad − komissiya − yetkazib berish.",
      month: 'Oy', orders: 'Buyurtmalar', revenue: 'Daromad', net: 'Sof', margin: 'Margin',
      current: 'joriy', total: 'Jami',
      exportFilename: 'pnl-hisoboti',
      colMonth: 'Oy', colRevenue: "Daromad (so'm)", colCommission: "Komissiya (so'm)",
      colDelivery: "Yetkazib berish (so'm)", colNet: "Sof (so'm)", colOrders: 'Buyurtmalar',
      chartTitle: 'Daromad va foyda dinamikasi', chartSubtitle: "Oylik ko'rsatkichlar",
      chartRevenue: 'Daromad', chartProfit: 'Sof foyda',
    },
    calculator: {
      title: 'Foyda kalkulyatori',
      subtitlePre: 'Uzum komissiyasi, qaytarish va logistika hisobga olingandan keyin',
      subtitleStrong: 'haqiqiy foydangizni', subtitlePost: 'bilib oling',
      productInfo: "Mahsulot ma'lumotlari",
      sellPrice: "Sotish narxi (so'm)", cost: "Tannarx (so'm)", logistics: "Logistika (so'm)",
      adSpend: "Reklama xarajati (so'm)", returnRate: 'Qaytarish foizi (%)', monthlyUnits: 'Oylik savdo (dona)',
      category: 'Kategoriya', commissionSuffix: 'komissiya',
      uzumCommission: 'Uzum komissiyasi:',
      enterToSee: "Natijani ko'rish uchun", enterPriceCost: 'narx va tannarxni kiriting',
      realityCheck: 'Reality Check — oylik hisob',
      youThink: 'Siz hisoblagan foyda', yourReal: 'Haqiqiy foydangiz',
      uzumTook: 'Uzum + xarajatlar olib ketdi',
      kept: 'Qoldi:', gone: 'Ketdi:',
      breakdownTitle: '1 dona mahsulotdan xarajatlar taqsimoti:',
      bdCommission: 'Uzum komissiyasi', bdCost: 'Tannarx', bdLogistics: 'Logistika',
      bdReturnLoss: 'Qaytarish zarari', bdAd: 'Reklama (dona)', netProfitUnit: 'Sof foyda (dona)',
      margin: 'Margin', roi: 'ROI', drr: 'DRR', breakeven: 'Zararlanmaslik',
      warnLossPre: 'Hozirgi narx bilan oyiga', warnLossStrong: "so'm zarar",
      warnLossMid: "ko'rmoqdasiz. Narxni kamida", warnLossEnd: "so'mga ko'taring.",
      warnMarginPre: 'Margin', warnMarginPost: "— juda past. Narx oshirish yoki tannarxni kamaytirish kerak. Tavsiya etilgan minimum: 20%.",
      warnDrrPre: 'DRR', warnDrrPost: '— reklama xarajati haddan oshgan. Optimal: 10–20%.',
      categories: ['Elektronika', 'Kompyuter texnikasi', 'Telefon va gadjetlar', 'Krossovkalar', 'Sport', 'Soatlar', "Uy-joy va bog'", 'Kiyim (erkaklar)', 'Kiyim (ayollar)', 'Kiyim (bolalar)', "Go'zallik va parvarish", "Sog'liq va tibbiyot", 'Oziq-ovqat', "O'yinchoqlar", 'Avtomobil', 'Boshqa'],
    },
    settings: {
      title: 'Sozlamalar', badge: "Sizning ma'lumotingiz", subtitle: 'Marketplace integratsiyalari',
      connected: 'Ulangan', notConnected: 'Ulanmagan',
      apiToken: 'API Token', oauthToken: 'OAuth Token', campaignId: 'Campaign ID',
      tokenPlaceholderHas: '••••••••  (yangilash uchun kiriting)', tokenPlaceholder: 'Token kiriting…',
      oauthPlaceholder: 'OAuth token kiriting…', campaignPlaceholder: 'Campaign ID (masalan: 12345678)',
      uzumHint1: 'Sozlamalar', uzumHint2: 'API integratsiya',
      yandexHint: 'OAuth token va Campaign ID',
      save: 'Saqlash', sync: 'Sinxronlash', syncing: 'Sinxronlanmoqda…',
      lastSyncPre: 'Oxirgi sinxr:', notSynced: 'Hali sinxronlanmagan',
      saveTokenFirst: 'Avval token saqlang', saveTokenCampaignFirst: 'Avval token va Campaign ID saqlang',
      shopCreated: "Do'kon yaratildi!", saved: 'Saqlandi!', err: 'Xato',
      serverErr: "Server bilan bog'lanishda xato",
      syncResult1: 'mahsulot,', syncResult2: 'buyurtma yangilandi.',
      syncAds: 'Reklamani sinxronlash', syncingAds: 'Reklama sinxronlanmoqda…',
      adsSynced: 'reklama statistikasi yangilandi.',
      wbHint: "Shaxsiy kabinet → Profil → API integratsiyalari → Yangi token",
      extToken: 'Kengayma Token', extTokenSub: 'Chrome extension uchun',
      currentToken: 'Joriy token', copy: 'Nusxalash', copied: 'Nusxalandi!', copyTitle: 'Nusxalash',
      extInstrPre: 'Ushbu tokenni', extInstrStrong: 'Chrome kengaytmasi → Options → Daromadchi token', extInstrPost: 'maydoniga joylashtiring',
      refresh: 'Yangilash', refreshing: 'Yangilanmoqda…',
      pwMin6: "Kamida 6 belgi bo'lishi kerak", pwMismatch: 'Parollar mos kelmadi',
      pwChanged: "Parol muvaffaqiyatli o'zgartirildi!",
      pwSetNew: "Yangi parol o'rnatish", pwSetNewDesc: 'Kamida 6 belgilik yangi parol kiriting',
      pwNew: 'Yangi parol', pwConfirm: 'Parolni tasdiqlang',
      pwSaving: 'Saqlanmoqda...', pwSave: 'Parolni saqlash',
      uzumAdsComing: 'Uzum Ads API hozircha mavjud emas — tez orada qo\'shiladi.',
      yandexAdsComing: 'Yandex Market reklama statistikasi — tez orada qo\'shiladi.',
    },
    sync: {
      title: 'Sinxronizatsiya holati',
      subtitle: 'Har bir marketplace bo\'yicha oxirgi sinxronizatsiya ma\'lumotlari',
      connected: 'Ulangan', notConnected: 'Ulanmagan',
      lastSync: 'Oxirgi sinxr:', notSynced: 'Hali sinxronlanmagan',
      products: 'mahsulot', orders: 'buyurtma',
      syncNow: 'Sinxronlash', syncing: 'Sinxronlanmoqda…',
      syncAll: 'Hammasini sinxronlash',
      noShops: 'Hech qanday do\'kon ulanmagan',
      noShopsDesc: 'Sozlamalar sahifasiga o\'tib, marketplace API tokeningizni ulang.',
      errorSync: 'Sinxronizatsiya xatosi',
      adsSync: 'Reklamani sinxronlash',
      adsSyncing: 'Reklama sinxronlanmoqda…',
      adsNotAvailable: 'Reklama API hozircha mavjud emas',
    },
    account: {
      title: 'Profil', subtitle: 'Akkaunt ma\'lumotlari va tarif rejasi',
      defaultUser: 'Foydalanuvchi', joined: "Ro'yxatdan o'tgan:",
      planTitle: 'Tarif rejasi', expires: 'Muddati:',
      planFree: 'Bepul', planPro: 'Pro', planProPlus: 'Pro+',
      freeDesc: "1 do'kon · 7 kunlik tarix", proDesc: "3 do'kon · Cheksiz tarix",
      proPlusDesc: "5 do'kon · Cheksiz tarix · Ustuvor qo'llab-quvvatlash",
      upgradePro: "Pro ga o'tish →",
      security: 'Xavfsizlik', password: 'Parol', passwordDesc: "Parolingizni o'zgartiring", change: "O'zgartirish",
    },
    abcxyz: {
      title: 'ABC-XYZ Tahlil',
      subtitle: "Mahsulotlaringizni daromad va talab barqarorligi bo'yicha tasniflang",
      badge: 'Inventar tahlili',
      classA: 'A sinf — asosiy daromad (80%)',
      classB: 'B sinf — o\'rtacha daromad (15%)',
      classC: 'C sinf — past daromad (5%)',
      classX: 'X — barqaror talab (≥10 ta sotilgan)',
      classY: 'Y — o\'rtacha talab (1–9 ta sotilgan)',
      classZ: 'Z — talab yo\'q (0 ta sotilgan)',
      all: 'Barchasi',
      product: 'Mahsulot', revenue: 'Daromad', revenueShare: 'Ulush', sold: 'Sotilgan',
      abcClass: 'ABC', xyzClass: 'XYZ', combined: 'Klass',
      noData: "Ma'lumot yo'q", noDataDesc: "Mahsulotlarni ko'rish uchun avval do'koningizni sinxronlang.",
      goSettings: "Sozlamalarga o'tish",
      interpretation: 'Talqin',
      axDesc: 'AX — eng muhim, barqaror mahsulotlar. Doimo stokda bo\'lsin.',
      azDesc: 'AZ — yuqori daromad, lekin noaniq talab. Ehtiyotkorlik bilan boshqaring.',
      cxDesc: 'CX — barqaror lekin past daromad. Assortimentni qayta ko\'ring.',
      czDesc: 'CZ — eng past ustuvorlik. Chiqarib tashlashni ko\'ring.',
    },
    market: {
      title: 'Bozor tadqiqoti', badge: 'Ommaviy ma\'lumot',
      subtitle: 'Raqiblar narxi, buyurtmalar va trend mahsulotlar',
      uzumNotice: "Uzum.uz ommaviy API'sidan foydalaniladi — hech qanday token shart emas. ",
      uzumYours: 'Sizning kategoriyalaringizdagi mahsulotlar belgilanadi.',
      uzumConnect: "Do'koningizni ulasangiz, o'z kategoriyalaringiz avtomatik belgilanadi.",
      connectLink: 'Ulash →',
      yandexNotice: 'Yandex Market katalogidan ma\'lumotlar sizning Partner API tokeningiz orqali yuklanadi. Kategoriya tanlang yoki mahsulot qidiring.',
      yandexNotConnected: 'Yandex Market ulanmagan',
      yandexNotConnectedDesc: "Yandex bozor tadqiqotini ko'rish uchun Sozlamalarda Partner API tokeningizni ulang.",
      yandexConnect: 'Yandex ulash',
      minPrice: 'Min narx', avgPrice: "O'rtacha narx", maxPrice: 'Max narx', totalOrders: 'Jami buyurtma',
      topProducts: "Top mahsulotlar — buyurtmalar bo'yicha",
      product: 'Mahsulot', price: 'Narx', orders: 'Buyurtmalar', rating: 'Reyting',
      yourCategory: 'Sizning kategoriya',
      topModels: 'Yandex Market — top modellar',
      model: 'Model', priceRange: 'Narx diapazoni', reviews: 'Sharhlar', offers: 'Takliflar',
      searchPlaceholder: 'Mahsulot nomini qidiring…', search: 'Qidirish',
      categories: 'Kategoriyalar', loading: 'Yuklanmoqda…',
      resultsSuffix: 'natijalari', productsCount: 'mahsulot', notFound: "Ma'lumot topilmadi",
      sortOrders: 'Buyurtmalar ↓', sortPriceAsc: 'Narx ↑', sortPriceDesc: 'Narx ↓', sortRating: 'Reyting ↓',
      sortOpinions: 'Fikrlar ↓', sortPrice: 'Narx', sortQuality: 'Sifat',
      estRevenue: 'Taxminiy daromad', estRevenueNote: '* WB uchun: sharhlar × 15 × narx (sanoat hisob-kitobi)',
      sortRevenue: 'Daromad ↓', topRevenueProducts: 'Raqobatchilar daromadi',
      revenueCol: 'Taxm. daromad', trending: 'Trend',
    },
    advertising: {
      kpiSpend: 'Jami sarflar', kpiImpressions: "Ko'rsatuvlar", kpiClicks: 'Kliklar',
      kpiOrders: 'Buyurtmalar', kpiRevenue: 'Daromad', kpiDrr: "O'rtacha DRR",
      tabAll: 'Hammasi',
      colCampaign: 'Kampaniya', colType: 'Tur', colStatus: 'Holat', colSpend: 'Sarflar',
      colImpressions: "Ko'rs.", colClicks: 'Kliklar', colCtr: 'CTR',
      colOrders: 'Buyurtma', colRevenue: 'Daromad', colDrr: 'DRR',
      statusActive: 'Faol', statusPaused: "To'xtatilgan", statusEnded: 'Yakunlangan',
      legendNoSale: "Sarflar bor, sotuv yo'q",
      myPrice: 'Mening narxim', minComp: 'Min raqobatchi',
      pageTitle: 'Reklama', pageSubtitle: 'CPC va CPO reklama kampaniyalari tahlili',
      noData: "Reklama ma'lumotlari yo'q", noDataDesc: "Ma'lumotlar ko'rsatilishi uchun do'konni sinxronlang. Siz quyidagi savdo maydonchalarida reklama boshqarish kabinetiga o'tishingiz mumkin:",
      goUzum: "Uzum seller kabinetiga o'tish", goWb: 'Wildberries kabinetiga o\'tish', goYandex: 'Yandex Market kabinetiga o\'tish',
    },
    reviews: {
      kpiTotal: 'Jami izohlar', kpiAvgRating: "O'rtacha reyting",
      kpiUnanswered: 'Javobsiz', kpiNegative: 'Salbiy',
      tabAll: 'Hammasi', tabUnanswered: 'Javobsiz', tabNegative: 'Salbiy', tabPositive: 'Ijobiy',
      searchPlaceholder: 'Qidirish...',
      sentPositive: 'Ijobiy', sentNegative: 'Salbiy', sentNeutral: 'Neytral',
      needReply: 'Javob kerak', replied: 'Javob berildi',
      replyBtn: 'Javob', yourReply: 'Sizning javobingiz:', replyLabel: 'Javob yozing:',
      replyPlaceholder: 'Mijozga javobingizni yozing...', replySend: 'Yuborish', replyCancel: 'Bekor',
      notFound: 'Izoh topilmadi',
    },
    payouts: {
      kpiTotalPaid: "Jami to'langan", kpiPending: 'Kutilayotgan', kpiAvg: "O'rtacha to'lov",
      perPeriod: 'har bir davr', periods: 'ta davr',
      statusPaid: "To'langan", statusProcessing: 'Jarayonda', statusPending: 'Kutilmoqda',
      segCommission: 'Komissiya', segDelivery: 'Yetkazish', segReturns: 'Qaytarishlar',
      segAd: 'Reklama', segAcquiring: 'Ekvayring', segTax: 'Soliq', segOther: 'Boshqa',
      deductionsTitle: 'Chegirmalar tafsiloti', totalDeductions: 'Jami chegirmalar',
      colPeriod: 'Davr', colOrders: 'Buyurtmalar', colGross: 'Brutto',
      colCommission: 'Komissiya', colDelivery: 'Yetkazish', colReturns: 'Qaytarish',
      colAd: 'Reklama', colTax: 'Soliq', colNet: "Sof to'lov", colStatus: 'Holat',
    },
    seasonality: {
      insightBest: 'Eng yaxshi oy', insightLow: 'Eng past oy',
      insightGrowth: "O'sish", insightCategory: 'Kategoriya',
      insightBestSub: "Ko'proq zaxira oling", insightLowSub: 'Zaxirani kamaytiring',
      insightGrowthSub: 'Yillik trend',
      chartSubtitle: '12 oylik sotuv daromadi', growthLabel: "o'sish",
      legendPeak: 'Eng yuqori oy', legendLow: 'Eng past oy',
      colMonth: 'Oy', colRevenue: 'Daromad', colOrders: 'Buyurtmalar',
      colAvgCheck: "O'rtacha chek", colActivity: 'Faollik',
      tagBest: 'Eng yaxshi', tagLow: 'Eng past',
      recTitle: 'Tavsiya',
      recPeak1: 'oyida eng yuqori sotuv kuzatiladi. Shu oydan',
      recPeak2: '1–2 oy oldin',
      recPeak3: 'yetarli zaxira to\'plang.',
      recLow1: 'oyida sotuv pasayadi — bu davrda reklama xarajatini kamaytiring.',
      tooltipRevenue: 'Daromad:', tooltipOrders: 'Buyurtmalar:', tooltipAvgCheck: "O'rtacha chek:",
    },
    stockAlerts: {
      kpiTotal: 'Jami ogohlantirishlar', kpiCritical: 'Kritik (≤ 3 kun)', kpiWarning: 'Ogohlantirish (≤ 7 kun)',
      stockHeader: 'Ombor holati',
      settingsTitle: 'Ogohlantirish sozlamalari', settingsThreshold: 'Kritik zaxira chegarasi (dona)',
      savingBtn: 'Saqlanmoqda…', savedBtn: 'Saqlandi ✓', saveBtn: 'Saqlash',
      telegramHint: 'Telegram botini yaratish uchun @BotFather ga murojaat qiling',
      colProduct: 'Mahsulot', colSku: 'SKU', colStock: 'Zaxira',
      colThreshold: 'Chegara', colDaysLeft: 'Qolgan kunlar',
      colDailyStock: 'Kunlik sotuv', colStatus: 'Holat',
      statusCritical: 'Kritik', statusWarning: 'Ogohlantirish', statusWatching: 'Kuzatuv',
      emptyTitle: 'Barcha mahsulotlar yetarli',
      emptyDesc: "Kritik zaxira darajasiga yetgan mahsulotlar yo'q",
      daysSuffix: 'kun', perDay: '/kun', units: 'dona',
    },
    priceTracking: {
      kpiProducts: 'Kuzatilayotgan mahsulotlar', kpiLowest: 'Eng arzon narx',
      kpiHighest: 'Qimmat / Eng qimmat', kpiAvgGap: "O'rtacha narx farqi",
      kpiProductSub: 'mahsulot',
      tableTitle: 'Raqobat narxlari',
      tabAll: 'Barchasi', tabLowest: 'Eng arzon', tabCompetitive: 'Raqobatbardosh', tabHigh: 'Qimmat',
      colProduct: 'Mahsulot', colMyPrice: 'Mening narxim', colMinComp: 'Min raqobatchi',
      colAvgMarket: "O'rt. bozor", colGap: 'Farq', colPosition: 'Pozitsiya',
      colCompetitors: 'Raqobatchilar', colLastCheck: "So'nggi tekshiruv",
      posLowest: 'Eng arzon', posCompetitive: 'Raqobatbardosh', posHigh: 'Qimmatroq', posHighest: 'Eng qimmat',
      myPrice: 'Mening narxim', minComp: 'Min raqobatchi',
      emptyMsg: 'Bu filtrdagi mahsulotlar topilmadi',
      infoText: "Ma'lumotlar har 6 soatda yangilanadi. Uzum API orqali real narxlar sinxronlanadi.",
      priceDynamics: 'Narx dinamikasi',
    },
    dataState: {
      statusReady: 'Tayyor', statusDegraded: 'Degradatsiya', statusError: 'Xato', statusPending: 'Kutilmoqda',
      clickToSelect: 'Tanlash uchun bosing',
      selectedDays: 'kun tanlangan', resyncBtn: 'Qayta yuklash', cancelBtn: 'Bekor',
      last30Days: "So'nggi 30 kun",
      colDate: 'Sana', colStatus: 'Holat', colProducts: 'Mahsulotlar', colRevenue: 'Daromad', colError: 'Xato',
      legendClick: 'Kun ustiga bosib tanlang → "Qayta yuklash" tugmasi paydo bo\'ladi',
    },
    referral: {
      howTitle: 'Qanday ishlaydi?',
      step1: 'Referal havolangizni nusxalang',
      step2: "Do'stingiz ro'yxatdan o'tadi",
      step3: "Har bir faol do'st uchun 50 000 so'm mukofot",
      yourLink: 'Sizning referal havolangiz',
      yourCode: '— sizning kodingiz',
      copyBtn: 'Nusxalash', copiedBtn: 'Nusxalandi!',
      kpiTotal: 'Jami taklif', kpiActive: 'Faol',
      kpiPending: 'Kutilmoqda', kpiReward: 'Jami mukofot',
      tableTitle: 'Taklif qilingan foydalanuvchilar',
      colNum: '#', colDate: 'Sana', colStatus: 'Holat', colActivated: 'Faollashdi', colReward: 'Mukofot',
      statusActive: 'Faol', statusPaid: "To'langan", statusPending: 'Kutilmoqda',
      emptyTitle: 'Hali hech kim taklif qilinmagan',
      emptyDesc: 'Yuqoridagi havolani ulashing va mukofot oling',
    },
    keywords: {
      title: 'Qidiruv iboralari',
      subtitle: "Har bir mahsulotingiz qaysi kalit so'zlar orqali topilayotgani, nechta taassurot va bosish olayotgani. CTR va o'rtacha pozitsiyani kuzatib boring.",
      demoNotice: "Demo ko'rinish.",
      demoDesc: "Quyidagi raqamlar namunali ma'lumotlar — sizning haqiqiy mahsulotlaringiz emas. Uzum Market qidiruv tahlili funksiyasi hali ishlab chiqilmoqda.",
      kpiImpressions: 'Jami taassurotlar', kpiClicks: 'Jami bosishlar',
      kpiCtr: "O'rtacha CTR", kpiGrowing: "O'sib borayotgan",
      kpiGrowingUnit: 'ta',
      searchPlaceholder: "Mahsulot yoki kalit so'z...",
      tabAll: 'Barcha', tabGrowing: "O'sib borayotgan", tabDeclining: 'Tushib borayotgan',
      colProduct: 'Mahsulot nomi', colKeywords: "Kalit so'zlar",
      colImpressions: 'Taassurotlar', colClicks: 'Bosishlar',
      colCtr: 'CTR', colPosition: 'Pozitsiya', colTrend: 'Trend',
      notFound: 'Natija topilmadi',
      showing: "ta mahsulot ko'rsatilmoqda",
    },
  },
  en: {
    nav: {
      dashboard: 'Dashboard', products: 'Products', orders: 'Orders',
      analytics: 'Analytics', pnl: 'P&L Report', calculator: 'Calculator',
      market: 'Market Research', settings: 'Settings', profile: 'Profile', logout: 'Sign out',
      store: 'My Store', bozor: 'Market', sync: 'Sync Status',
      abcxyz: 'ABC-XYZ',
    },
    dashboard: {
      title: 'Dashboard', subtitle: 'Welcome! This is your store analytics.',
      badge: 'Your data', sync: 'Sync',
      all: 'All', revenue: 'Total revenue', profit: 'Net profit',
      orders: 'Orders', stock: 'Stock',
      recentOrders: 'Recent orders', topProducts: 'Top products',
      viewAll: 'View all', noData: 'No data yet',
      noDataDesc: 'Go to Settings, enter your API token and start syncing. Uzum Market, Yandex Market and Wildberries are supported.',
      noDataSynced: 'Sync ran but no data was found',
      noDataSyncedDesc: "The API returned no orders or products. Click the 'Sync' button above to try again.",
      goSettings: 'Go to settings',
      dailyRevenue: 'Daily revenue', categories: 'Categories',
      product: 'Product', profit2: 'Profit', sold: 'Sold',
      syncing: 'Syncing...', done: 'Done!', err: 'Error',
      last: 'Last', daysSuffix: 'days',
      yesterday: 'Yesterday', thisMonth: 'This month', vsPrev: 'vs prior period',
      customize: 'Customize', widgetKpis: 'KPI Cards', widgetAlerts: 'Stock Alerts', widgetChart: 'Revenue Chart', widgetCategories: 'Categories',
      noProducts: 'No products', noProductsDesc: 'Sync your store or add products.',
    },
    export: {
      download: 'Download', xlsx: 'Excel (.xlsx)', csv: 'CSV', pdf: 'PDF (print)',
    },
    status: {
      pending: 'Pending', confirmed: 'Confirmed', delivered: 'Delivered',
      cancelled: 'Cancelled', returned: 'Returned',
    },
    products: {
      title: 'Products', count: 'products', empty: 'No products',
      emptyDesc: 'Connect your Uzum store and start syncing — products will be imported automatically.',
      goSettings: 'Go to settings',
      all: 'All', searchPlaceholder: 'Product name, SKU or category...',
      filter: '(filtered)', notFound: 'Nothing found',
      product: 'Product', category: 'Category', price: 'Price', cost: 'Cost',
      profit: 'Profit', margin: 'Margin', sold: 'Sold', stock: 'Stock',
      exportFilename: 'products',
      colProduct: 'Product', colSku: 'SKU', colCategory: 'Category',
      colPrice: "Price (so'm)", colCost: "Cost (so'm)", colProfit: "Profit (so'm)",
      colMargin: 'Margin (%)', colSold: 'Sold', colStock: 'Stock',
      filterLowStock: 'Low stock', filterOutOfStock: 'Out of stock',
      filterNoOrders: 'No orders', filterHighMargin: 'High margin',
      filterHighDrr: 'High DRR', filterWithAds: 'With ads',
      columns: 'Columns', presetDefault: 'Default', presetCompact: 'Compact',
      drr: 'DRR', adSpend: 'Ad spend', impressions: 'Views', clicks: 'Clicks', ctr: 'CTR',
      indicators: 'Indicators',
      drrGreen: 'DRR green (max %)', drrYellow: 'DRR yellow (max %)', drrRedLabel: 'DRR red (and above)',
      stockYellowLabel: 'Yellow stock (units)', stockRedLabel: 'Red stock (units)',
      indicatorsHint: 'Color indicators are applied to the products table',
    },
    orders: {
      title: 'Orders', count: 'orders', empty: 'No orders',
      emptyDesc: 'Connect your Uzum store and start syncing — orders will be imported automatically.',
      goSettings: 'Go to settings',
      pending: 'Pending', confirmed: 'Confirmed', delivered: 'Delivered',
      cancelledFull: 'Cancelled', returned: 'Returned',
      all: 'All', cancelled: 'Cancelled',
      searchPlaceholder: 'Order ID or marketplace...', notFound: 'Nothing found',
      orderId: 'Order ID', marketplace: 'Marketplace', date: 'Date',
      revenue: 'Revenue', commission: 'Commission', delivery: 'Delivery',
      items: 'Items', statusCol: 'Status',
      exportFilename: 'orders',
      colDate: 'Date', colRevenue: "Revenue (so'm)", colCommission: "Commission (so'm)",
      colDelivery: "Delivery (so'm)",
    },
    analytics: {
      title: 'Advanced analytics', subtitle: 'Sales, ads, returns and time analysis',
      emptyAfterSync: 'Data will appear after syncing',
      noShop: 'No store connected',
      noShopDesc: 'Go to Settings, enter your Uzum API token and start syncing.',
      goSettings: 'Go to settings',
      freeBannerPre: 'Free plan: showing only the last', freeBannerDays: '7 days',
      freeBannerPost: 'of data. For more history', freeBannerLink: 'upgrade to Pro',
      daysSuffix: 'days',
      funnelTitle: 'Sales funnel',
      funnelImpressions: 'Impressions', funnelProductPage: 'Product page',
      funnelCart: 'Cart', funnelOrder: 'Order', funnelProfit: 'Profit',
      mpData: 'Marketplace data', marginSuffix: 'margin',
      funnelNote: '* Impressions, page views and cart data will be added via the marketplace API.',
      rankingTitle: 'Product profit ranking',
      colProductName: 'Product name', colSales: 'Sales', colRevenue: 'Revenue',
      colCommission: 'Commission (~12%)', colProfitUnit: 'Profit / unit', colProfitability: 'Profitability',
      weeklyTitle: 'Weekly comparison',
      colMetric: 'Metric', colThisWeek: 'This week', colLastWeek: 'Last week', colDiff: 'Diff',
      mOrders: 'Orders', mRevenue: 'Revenue', mProfit: 'Profit', mReturns: 'Returns',
      adTitle: 'Ad efficiency',
      adTotalSpend: 'Total ad spend (est.)', adTotalRevenue: 'Total revenue', adDrrTotal: 'DRR (total)',
      colProduct: 'Product', colAdSpend: 'Ad spend', colDrr: 'DRR %',
      adNoteLabel: 'Note:',
      adNote: 'Ad spend is currently estimated based on commission. Real Uzum Ads data will be added soon.',
      returnsTitle: 'Returns analysis',
      retTotal: 'Total returns', retCount: '', retRate: 'Return rate', retValue: 'Return value',
      retLevel: 'Return level (this period)', retAllShops: 'All stores',
      retNote: '* For per-product return analysis we will add the order ↔ product link via the API.',
      priceTitle: 'Price positioning',
      priceNote: 'Competitor prices will be added soon — for now the category average is shown.',
      colYourPrice: 'Your price', colCatAvg: 'Category average', colDiff2: 'Diff %',
      legendBelow: 'Below average (−10%)', legendAround: 'Around average', legendAbove: 'Above average (+20%)',
      timeTitle: 'Best selling time',
      byDay: 'By day of week', byHour: 'By hour',
      days: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    },
    pnl: {
      title: 'Profit & loss report',
      subtitleEmpty: 'Data will appear once the store is synced',
      subtitle: 'Last 6 months · Revenue, commission and delivery costs',
      empty: 'No data',
      emptyDesc: 'To view the report, first connect your Uzum store and run a sync.',
      goSettings: 'Go to settings',
      totalRevenue: 'Total revenue', commission: 'Commission', delivery: 'Delivery',
      netNoComm: 'Net (no commission)',
      cogsNote: 'Cost of goods (COGS) is not included in the calculation — to add this column, update your product purchase prices in settings. Net = revenue − commission − delivery.',
      month: 'Month', orders: 'Orders', revenue: 'Revenue', net: 'Net', margin: 'Margin',
      current: 'current', total: 'Total',
      exportFilename: 'pnl-report',
      colMonth: 'Month', colRevenue: "Revenue (so'm)", colCommission: "Commission (so'm)",
      colDelivery: "Delivery (so'm)", colNet: "Net (so'm)", colOrders: 'Orders',
      chartTitle: 'Revenue and profit dynamics', chartSubtitle: 'Monthly metrics',
      chartRevenue: 'Revenue', chartProfit: 'Net profit',
    },
    calculator: {
      title: 'Profit calculator',
      subtitlePre: 'Find out your',
      subtitleStrong: 'real profit', subtitlePost: 'after Uzum commission, returns and logistics',
      productInfo: 'Product details',
      sellPrice: "Selling price (so'm)", cost: "Cost (so'm)", logistics: "Logistics (so'm)",
      adSpend: "Ad spend (so'm)", returnRate: 'Return rate (%)', monthlyUnits: 'Monthly sales (units)',
      category: 'Category', commissionSuffix: 'commission',
      uzumCommission: 'Uzum commission:',
      enterToSee: 'To see the result', enterPriceCost: 'enter price and cost',
      realityCheck: 'Reality Check — monthly estimate',
      youThink: 'Profit you expected', yourReal: 'Your real profit',
      uzumTook: 'Uzum + expenses took',
      kept: 'Kept:', gone: 'Gone:',
      breakdownTitle: 'Cost breakdown per unit:',
      bdCommission: 'Uzum commission', bdCost: 'Cost', bdLogistics: 'Logistics',
      bdReturnLoss: 'Return loss', bdAd: 'Ad (per unit)', netProfitUnit: 'Net profit (per unit)',
      margin: 'Margin', roi: 'ROI', drr: 'DRR', breakeven: 'Break-even',
      warnLossPre: 'At the current price you lose', warnLossStrong: "so'm",
      warnLossMid: 'per month. Raise the price to at least', warnLossEnd: "so'm.",
      warnMarginPre: 'Margin', warnMarginPost: '— too low. You need to raise the price or reduce the cost. Recommended minimum: 20%.',
      warnDrrPre: 'DRR', warnDrrPost: '— ad spend is too high. Optimal: 10–20%.',
      categories: ['Electronics', 'Computer hardware', 'Phones & gadgets', 'Sneakers', 'Sports', 'Watches', 'Home & garden', 'Clothing (men)', 'Clothing (women)', 'Clothing (kids)', 'Beauty & care', 'Health & medicine', 'Groceries', 'Toys', 'Automotive', 'Other'],
    },
    settings: {
      title: 'Settings', badge: 'Your data', subtitle: 'Marketplace integrations',
      connected: 'Connected', notConnected: 'Not connected',
      apiToken: 'API Token', oauthToken: 'OAuth Token', campaignId: 'Campaign ID',
      tokenPlaceholderHas: '••••••••  (enter to update)', tokenPlaceholder: 'Enter token…',
      oauthPlaceholder: 'Enter OAuth token…', campaignPlaceholder: 'Campaign ID (e.g. 12345678)',
      uzumHint1: 'Settings', uzumHint2: 'API integration',
      yandexHint: 'OAuth token and Campaign ID',
      save: 'Save', sync: 'Sync', syncing: 'Syncing…',
      lastSyncPre: 'Last sync:', notSynced: 'Not synced yet',
      saveTokenFirst: 'Save a token first', saveTokenCampaignFirst: 'Save token and Campaign ID first',
      shopCreated: 'Store created!', saved: 'Saved!', err: 'Error',
      serverErr: 'Error connecting to the server',
      syncResult1: 'products,', syncResult2: 'orders updated.',
      syncAds: 'Sync ads', syncingAds: 'Syncing ads…',
      adsSynced: 'ad stats updated.',
      wbHint: 'Personal account → Profile → API integrations → New token',
      extToken: 'Extension Token', extTokenSub: 'For the Chrome extension',
      currentToken: 'Current token', copy: 'Copy', copied: 'Copied!', copyTitle: 'Copy',
      extInstrPre: 'Paste this token into the', extInstrStrong: 'Chrome extension → Options → Daromadchi token', extInstrPost: 'field',
      refresh: 'Refresh', refreshing: 'Refreshing…',
      pwMin6: 'Must be at least 6 characters', pwMismatch: 'Passwords do not match',
      pwChanged: 'Password changed successfully!',
      pwSetNew: 'Set a new password', pwSetNewDesc: 'Enter a new password of at least 6 characters',
      pwNew: 'New password', pwConfirm: 'Confirm password',
      pwSaving: 'Saving...', pwSave: 'Save password',
      uzumAdsComing: 'Uzum Ads API is not available yet — coming soon.',
      yandexAdsComing: 'Yandex Market ad statistics — coming soon.',
    },
    sync: {
      title: 'Sync Status',
      subtitle: 'Last sync information per marketplace',
      connected: 'Connected', notConnected: 'Not connected',
      lastSync: 'Last sync:', notSynced: 'Not synced yet',
      products: 'products', orders: 'orders',
      syncNow: 'Sync', syncing: 'Syncing…',
      syncAll: 'Sync all',
      noShops: 'No stores connected',
      noShopsDesc: 'Go to Settings and connect your marketplace API token.',
      errorSync: 'Sync error',
      adsSync: 'Sync ads',
      adsSyncing: 'Syncing ads…',
      adsNotAvailable: 'Ads API not available yet',
    },
    account: {
      title: 'Profile', subtitle: 'Account information and subscription plan',
      defaultUser: 'User', joined: 'Joined:',
      planTitle: 'Subscription plan', expires: 'Expires:',
      planFree: 'Free', planPro: 'Pro', planProPlus: 'Pro+',
      freeDesc: '1 store · 7-day history', proDesc: '3 stores · Unlimited history',
      proPlusDesc: '5 stores · Unlimited history · Priority support',
      upgradePro: 'Upgrade to Pro →',
      security: 'Security', password: 'Password', passwordDesc: 'Change your password', change: 'Change',
    },
    market: {
      title: 'Market research', badge: 'Public data',
      subtitle: 'Competitor prices, orders and trending products',
      uzumNotice: "The Uzum.uz public API is used — no token required. ",
      uzumYours: 'Products in your categories are highlighted.',
      uzumConnect: 'Connect your store and your own categories will be highlighted automatically.',
      connectLink: 'Connect →',
      yandexNotice: 'Data from the Yandex Market catalog is loaded via your Partner API token. Pick a category or search for a product.',
      yandexNotConnected: 'Yandex Market not connected',
      yandexNotConnectedDesc: 'To view Yandex market research, connect your Partner API token in Settings.',
      yandexConnect: 'Connect Yandex',
      minPrice: 'Min price', avgPrice: 'Average price', maxPrice: 'Max price', totalOrders: 'Total orders',
      topProducts: 'Top products — by orders',
      product: 'Product', price: 'Price', orders: 'Orders', rating: 'Rating',
      yourCategory: 'Your category',
      topModels: 'Yandex Market — top models',
      model: 'Model', priceRange: 'Price range', reviews: 'Reviews', offers: 'Offers',
      searchPlaceholder: 'Search product name…', search: 'Search',
      categories: 'Categories', loading: 'Loading…',
      resultsSuffix: 'results', productsCount: 'products', notFound: 'No data found',
      sortOrders: 'Orders ↓', sortPriceAsc: 'Price ↑', sortPriceDesc: 'Price ↓', sortRating: 'Rating ↓',
      sortOpinions: 'Reviews ↓', sortPrice: 'Price', sortQuality: 'Quality',
      estRevenue: 'Est. Revenue', estRevenueNote: '* WB: reviews × 15 × price (industry estimate)',
      sortRevenue: 'Revenue ↓', topRevenueProducts: 'Competitor Revenue',
      revenueCol: 'Est. Revenue', trending: 'Trending',
    },
    abcxyz: {
      title: 'ABC-XYZ Analysis',
      subtitle: 'Classify your products by revenue contribution and demand stability',
      badge: 'Inventory analysis',
      classA: 'Class A — key revenue (80%)',
      classB: 'Class B — mid revenue (15%)',
      classC: 'Class C — low revenue (5%)',
      classX: 'X — stable demand (≥10 sold)',
      classY: 'Y — moderate demand (1–9 sold)',
      classZ: 'Z — no demand (0 sold)',
      all: 'All',
      product: 'Product', revenue: 'Revenue', revenueShare: 'Share', sold: 'Sold',
      abcClass: 'ABC', xyzClass: 'XYZ', combined: 'Class',
      noData: 'No data', noDataDesc: 'Sync your store to see product analysis.',
      goSettings: 'Go to settings',
      interpretation: 'Interpretation',
      axDesc: 'AX — most important, stable products. Always keep in stock.',
      azDesc: 'AZ — high revenue but unpredictable demand. Manage carefully.',
      cxDesc: 'CX — stable but low revenue. Review your assortment.',
      czDesc: 'CZ — lowest priority. Consider removing from assortment.',
    },
    advertising: {
      kpiSpend: 'Total spend', kpiImpressions: 'Impressions', kpiClicks: 'Clicks',
      kpiOrders: 'Orders', kpiRevenue: 'Revenue', kpiDrr: 'Avg DRR',
      tabAll: 'All',
      colCampaign: 'Campaign', colType: 'Type', colStatus: 'Status', colSpend: 'Spend',
      colImpressions: 'Impr.', colClicks: 'Clicks', colCtr: 'CTR',
      colOrders: 'Orders', colRevenue: 'Revenue', colDrr: 'DRR',
      statusActive: 'Active', statusPaused: 'Paused', statusEnded: 'Ended',
      legendNoSale: 'Spend with no sales',
      myPrice: 'My price', minComp: 'Min competitor',
      pageTitle: 'Advertising', pageSubtitle: 'CPC and CPO ad campaign analytics',
      noData: 'No advertising data', noDataDesc: 'Sync your store to see ad data. You can also manage your campaigns directly in the marketplace seller portals:',
      goUzum: 'Go to Uzum seller portal', goWb: 'Go to Wildberries portal', goYandex: 'Go to Yandex Market portal',
    },
    reviews: {
      kpiTotal: 'Total reviews', kpiAvgRating: 'Avg rating',
      kpiUnanswered: 'Unanswered', kpiNegative: 'Negative',
      tabAll: 'All', tabUnanswered: 'Unanswered', tabNegative: 'Negative', tabPositive: 'Positive',
      searchPlaceholder: 'Search...',
      sentPositive: 'Positive', sentNegative: 'Negative', sentNeutral: 'Neutral',
      needReply: 'Needs reply', replied: 'Replied',
      replyBtn: 'Reply', yourReply: 'Your reply:', replyLabel: 'Write reply:',
      replyPlaceholder: 'Write your reply to the customer...', replySend: 'Send', replyCancel: 'Cancel',
      notFound: 'No reviews found',
    },
    payouts: {
      kpiTotalPaid: 'Total paid', kpiPending: 'Pending', kpiAvg: 'Avg payout',
      perPeriod: 'per period', periods: 'periods',
      statusPaid: 'Paid', statusProcessing: 'Processing', statusPending: 'Pending',
      segCommission: 'Commission', segDelivery: 'Delivery', segReturns: 'Returns',
      segAd: 'Advertising', segAcquiring: 'Acquiring', segTax: 'Tax', segOther: 'Other',
      deductionsTitle: 'Deduction details', totalDeductions: 'Total deductions',
      colPeriod: 'Period', colOrders: 'Orders', colGross: 'Gross',
      colCommission: 'Commission', colDelivery: 'Delivery', colReturns: 'Returns',
      colAd: 'Advertising', colTax: 'Tax', colNet: 'Net payout', colStatus: 'Status',
    },
    seasonality: {
      insightBest: 'Best month', insightLow: 'Lowest month',
      insightGrowth: 'Growth', insightCategory: 'Category',
      insightBestSub: 'Stock up more', insightLowSub: 'Reduce stock',
      insightGrowthSub: 'Annual trend',
      chartSubtitle: '12-month sales revenue', growthLabel: 'growth',
      legendPeak: 'Peak month', legendLow: 'Lowest month',
      colMonth: 'Month', colRevenue: 'Revenue', colOrders: 'Orders',
      colAvgCheck: 'Avg order', colActivity: 'Activity',
      tagBest: 'Best', tagLow: 'Lowest',
      recTitle: 'Recommendation',
      recPeak1: 'has the highest sales. Stock up', recPeak2: '1–2 months', recPeak3: 'before this month.',
      recLow1: 'has low sales — reduce ad spend during this period.',
      tooltipRevenue: 'Revenue:', tooltipOrders: 'Orders:', tooltipAvgCheck: 'Avg order:',
    },
    stockAlerts: {
      kpiTotal: 'Total alerts', kpiCritical: 'Critical (≤ 3 days)', kpiWarning: 'Warning (≤ 7 days)',
      stockHeader: 'Inventory status',
      settingsTitle: 'Alert settings', settingsThreshold: 'Critical stock threshold (units)',
      savingBtn: 'Saving…', savedBtn: 'Saved ✓', saveBtn: 'Save',
      telegramHint: 'To create a Telegram bot, contact @BotFather',
      colProduct: 'Product', colSku: 'SKU', colStock: 'Stock',
      colThreshold: 'Threshold', colDaysLeft: 'Days left',
      colDailyStock: 'Daily sales', colStatus: 'Status',
      statusCritical: 'Critical', statusWarning: 'Warning', statusWatching: 'Watching',
      emptyTitle: 'All products have sufficient stock',
      emptyDesc: 'No products have reached the critical stock threshold',
      daysSuffix: 'days', perDay: '/day', units: 'units',
    },
    priceTracking: {
      kpiProducts: 'Tracked products', kpiLowest: 'Lowest price',
      kpiHighest: 'High / Highest', kpiAvgGap: 'Avg price gap',
      kpiProductSub: 'products',
      tableTitle: 'Competitor prices',
      tabAll: 'All', tabLowest: 'Lowest', tabCompetitive: 'Competitive', tabHigh: 'High',
      colProduct: 'Product', colMyPrice: 'My price', colMinComp: 'Min competitor',
      colAvgMarket: 'Avg market', colGap: 'Gap', colPosition: 'Position',
      colCompetitors: 'Competitors', colLastCheck: 'Last check',
      posLowest: 'Lowest', posCompetitive: 'Competitive', posHigh: 'High', posHighest: 'Highest',
      myPrice: 'My price', minComp: 'Min competitor',
      emptyMsg: 'No products found for this filter',
      infoText: 'Data updated every 6 hours. Real prices synced via Uzum API.',
      priceDynamics: 'Price dynamics',
    },
    dataState: {
      statusReady: 'Ready', statusDegraded: 'Degraded', statusError: 'Error', statusPending: 'Pending',
      clickToSelect: 'Click to select',
      selectedDays: 'days selected', resyncBtn: 'Resync', cancelBtn: 'Cancel',
      last30Days: 'Last 30 days',
      colDate: 'Date', colStatus: 'Status', colProducts: 'Products', colRevenue: 'Revenue', colError: 'Error',
      legendClick: 'Click a day to select → "Resync" button appears',
    },
    referral: {
      howTitle: 'How it works?',
      step1: 'Copy your referral link',
      step2: 'Your friend signs up',
      step3: 'Earn 50,000 som for each active friend',
      yourLink: 'Your referral link',
      yourCode: '— your code',
      copyBtn: 'Copy', copiedBtn: 'Copied!',
      kpiTotal: 'Total referred', kpiActive: 'Active',
      kpiPending: 'Pending', kpiReward: 'Total reward',
      tableTitle: 'Referred users',
      colNum: '#', colDate: 'Date', colStatus: 'Status', colActivated: 'Activated', colReward: 'Reward',
      statusActive: 'Active', statusPaid: 'Paid', statusPending: 'Pending',
      emptyTitle: 'No one referred yet',
      emptyDesc: 'Share the link above and earn rewards',
    },
    keywords: {
      title: 'Search phrases',
      subtitle: 'Which keywords your products are found by, how many impressions and clicks they get. Track CTR and average position.',
      demoNotice: 'Demo view.',
      demoDesc: 'The numbers below are sample data — not your real products. Uzum Market search analytics feature is in development.',
      kpiImpressions: 'Total impressions', kpiClicks: 'Total clicks',
      kpiCtr: 'Avg CTR', kpiGrowing: 'Growing',
      kpiGrowingUnit: '',
      searchPlaceholder: 'Product or keyword...',
      tabAll: 'All', tabGrowing: 'Growing', tabDeclining: 'Declining',
      colProduct: 'Product name', colKeywords: 'Keywords',
      colImpressions: 'Impressions', colClicks: 'Clicks',
      colCtr: 'CTR', colPosition: 'Position', colTrend: 'Trend',
      notFound: 'No results found',
      showing: 'products shown',
    },
  },
  ru: {
    nav: {
      dashboard: 'Дашборд', products: 'Товары', orders: 'Заказы',
      analytics: 'Аналитика', pnl: 'Отчёт P&L', calculator: 'Калькулятор',
      market: 'Исследование рынка', settings: 'Настройки', profile: 'Профиль', logout: 'Выйти',
      store: 'Мой магазин', bozor: 'Рынок', sync: 'Синхронизация', abcxyz: 'ABC-XYZ',
    },
    dashboard: {
      title: 'Дашборд', subtitle: 'Добро пожаловать! Это аналитика вашего магазина.',
      badge: 'Ваши данные', sync: 'Синхронизировать',
      all: 'Все', revenue: 'Общая выручка', profit: 'Чистая прибыль',
      orders: 'Заказы', stock: 'Остатки',
      recentOrders: 'Последние заказы', topProducts: 'Топ товаров',
      viewAll: 'Смотреть все', noData: 'Данных пока нет',
      noDataDesc: 'Перейдите в Настройки, введите API-токен и запустите синхронизацию. Поддерживаются Uzum Market, Yandex Market и Wildberries.',
      noDataSynced: 'Синхронизация выполнена, но данные не найдены',
      noDataSyncedDesc: "API не вернул заказов или товаров. Нажмите кнопку 'Синхронизировать' выше и попробуйте ещё раз.",
      goSettings: 'Перейти в настройки',
      dailyRevenue: 'Дневная выручка', categories: 'Категории',
      product: 'Товар', profit2: 'Прибыль', sold: 'Продано',
      syncing: 'Синхронизирую...', done: 'Готово!', err: 'Ошибка',
      last: 'Последние', daysSuffix: 'дн.',
      yesterday: 'Вчера', thisMonth: 'Тек. месяц', vsPrev: 'к прошлому периоду',
      customize: 'Настроить', widgetKpis: 'KPI Карточки', widgetAlerts: 'Уведомления о запасах', widgetChart: 'График выручки', widgetCategories: 'Категории',
      noProducts: 'Нет товаров', noProductsDesc: 'Синхронизируйте магазин или добавьте товары.',
    },
    export: {
      download: 'Скачать', xlsx: 'Excel (.xlsx)', csv: 'CSV', pdf: 'PDF (печать)',
    },
    status: {
      pending: 'Ожидает', confirmed: 'Подтверждён', delivered: 'Доставлен',
      cancelled: 'Отменён', returned: 'Возвращён',
    },
    products: {
      title: 'Товары', count: 'товаров', empty: 'Нет товаров',
      emptyDesc: 'Подключите магазин Uzum и запустите синхронизацию — товары импортируются автоматически.',
      goSettings: 'Перейти в настройки',
      all: 'Все', searchPlaceholder: 'Название товара, SKU или категория...',
      filter: '(фильтр)', notFound: 'Ничего не найдено',
      product: 'Товар', category: 'Категория', price: 'Цена', cost: 'Себестоимость',
      profit: 'Прибыль', margin: 'Маржа', sold: 'Продано', stock: 'Остаток',
      exportFilename: 'tovary',
      colProduct: 'Товар', colSku: 'SKU', colCategory: 'Категория',
      colPrice: "Цена (so'm)", colCost: "Себестоимость (so'm)", colProfit: "Прибыль (so'm)",
      colMargin: 'Маржа (%)', colSold: 'Продано', colStock: 'Остаток',
      filterLowStock: 'Мало остатков', filterOutOfStock: 'Нет остатков',
      filterNoOrders: 'Без заказов', filterHighMargin: 'Высокая маржа',
      filterHighDrr: 'Высокий ДРР', filterWithAds: 'С рекламой',
      columns: 'Столбцы', presetDefault: 'По умолч.', presetCompact: 'Компактный',
      drr: 'ДРР', adSpend: 'Расход', impressions: 'Показы', clicks: 'Клики', ctr: 'CTR',
      indicators: 'Индикаторы',
      drrGreen: 'ДРР зелёный (макс %)', drrYellow: 'ДРР жёлтый (макс %)', drrRedLabel: 'ДРР красный (и выше)',
      stockYellowLabel: 'Жёлтый склад (шт.)', stockRedLabel: 'Красный склад (шт.)',
      indicatorsHint: 'Цветовые индикаторы применяются к таблице товаров',
    },
    orders: {
      title: 'Заказы', count: 'заказов', empty: 'Нет заказов',
      emptyDesc: 'Подключите магазин Uzum и запустите синхронизацию — заказы импортируются автоматически.',
      goSettings: 'Перейти в настройки',
      pending: 'Ожидает', confirmed: 'Подтверждён', delivered: 'Доставлен',
      cancelledFull: 'Отменён', returned: 'Возвращён',
      all: 'Все', cancelled: 'Отменён',
      searchPlaceholder: 'ID заказа или маркетплейс...', notFound: 'Ничего не найдено',
      orderId: 'ID заказа', marketplace: 'Маркетплейс', date: 'Дата',
      revenue: 'Выручка', commission: 'Комиссия', delivery: 'Доставка',
      items: 'Товары', statusCol: 'Статус',
      exportFilename: 'zakazy',
      colDate: 'Дата', colRevenue: "Выручка (so'm)", colCommission: "Комиссия (so'm)",
      colDelivery: "Доставка (so'm)",
    },
    analytics: {
      title: 'Расширенная аналитика', subtitle: 'Анализ продаж, рекламы, возвратов и времени',
      emptyAfterSync: 'Данные появятся после синхронизации',
      noShop: 'Магазин не подключён',
      noShopDesc: 'Перейдите в Настройки, введите API-токен Uzum и запустите синхронизацию.',
      goSettings: 'Перейти в настройки',
      freeBannerPre: 'Бесплатный тариф: показаны данные только за последние', freeBannerDays: '7 дней',
      freeBannerPost: '. Для большей истории', freeBannerLink: 'перейдите на Pro',
      daysSuffix: 'дн.',
      funnelTitle: 'Воронка продаж',
      funnelImpressions: 'Показы', funnelProductPage: 'Страница товара',
      funnelCart: 'Корзина', funnelOrder: 'Заказ', funnelProfit: 'Прибыль',
      mpData: 'Данные маркетплейса', marginSuffix: 'маржа',
      funnelNote: '* Показы, просмотры страниц и данные корзины будут добавлены через API маркетплейса.',
      rankingTitle: 'Рейтинг прибыльности товаров',
      colProductName: 'Название товара', colSales: 'Продажи', colRevenue: 'Выручка',
      colCommission: 'Комиссия (~12%)', colProfitUnit: 'Прибыль / шт.', colProfitability: 'Рентабельность',
      weeklyTitle: 'Сравнение по неделям',
      colMetric: 'Показатель', colThisWeek: 'Эта неделя', colLastWeek: 'Прошлая неделя', colDiff: 'Разница',
      mOrders: 'Заказы', mRevenue: 'Выручка', mProfit: 'Прибыль', mReturns: 'Возвраты',
      adTitle: 'Эффективность рекламы',
      adTotalSpend: 'Всего на рекламу (прибл.)', adTotalRevenue: 'Общая выручка', adDrrTotal: 'ДРР (всего)',
      colProduct: 'Товар', colAdSpend: 'Расход на рекламу', colDrr: 'ДРР %',
      adNoteLabel: 'Примечание:',
      adNote: 'Расход на рекламу пока рассчитывается приблизительно на основе комиссии. Реальные данные Uzum Ads будут добавлены в ближайшее время.',
      returnsTitle: 'Анализ возвратов',
      retTotal: 'Всего возвратов', retCount: 'шт.', retRate: 'Процент возвратов', retValue: 'Стоимость возвратов',
      retLevel: 'Уровень возвратов (за период)', retAllShops: 'Все магазины',
      retNote: '* Для анализа возвратов по товарам мы добавим связь заказ ↔ товар через API.',
      priceTitle: 'Позиционирование по цене',
      priceNote: 'Цены конкурентов будут добавлены в ближайшее время — пока показано среднее по категории.',
      colYourPrice: 'Ваша цена', colCatAvg: 'Среднее по категории', colDiff2: 'Разница %',
      legendBelow: 'Ниже среднего (−10%)', legendAround: 'Около среднего', legendAbove: 'Выше среднего (+20%)',
      timeTitle: 'Лучшее время продаж',
      byDay: 'По дням недели', byHour: 'По часам',
      days: ['Воскресенье', 'Понедельник', 'Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота'],
    },
    pnl: {
      title: 'Отчёт о прибылях и убытках',
      subtitleEmpty: 'Данные появятся после синхронизации магазина',
      subtitle: 'Последние 6 месяцев · Выручка, комиссия и расходы на доставку',
      empty: 'Нет данных',
      emptyDesc: 'Чтобы увидеть отчёт, сначала подключите магазин Uzum и выполните синхронизацию.',
      goSettings: 'Перейти в настройки',
      totalRevenue: 'Общая выручка', commission: 'Комиссия', delivery: 'Доставка',
      netNoComm: 'Чистая (без комиссии)',
      cogsNote: 'Себестоимость (COGS) не учтена в расчёте — чтобы добавить этот столбец, обновите закупочные цены товаров в настройках. Чистая = выручка − комиссия − доставка.',
      month: 'Месяц', orders: 'Заказы', revenue: 'Выручка', net: 'Чистая', margin: 'Маржа',
      current: 'текущий', total: 'Итого',
      exportFilename: 'pnl-otchet',
      colMonth: 'Месяц', colRevenue: "Выручка (so'm)", colCommission: "Комиссия (so'm)",
      colDelivery: "Доставка (so'm)", colNet: "Чистая (so'm)", colOrders: 'Заказы',
      chartTitle: 'Динамика выручки и прибыли', chartSubtitle: 'Помесячные показатели',
      chartRevenue: 'Выручка', chartProfit: 'Чистая прибыль',
    },
    calculator: {
      title: 'Калькулятор прибыли',
      subtitlePre: 'Узнайте',
      subtitleStrong: 'реальную прибыль', subtitlePost: 'с учётом комиссии Uzum, возвратов и логистики',
      productInfo: 'Данные о товаре',
      sellPrice: "Цена продажи (so'm)", cost: "Себестоимость (so'm)", logistics: "Логистика (so'm)",
      adSpend: "Расход на рекламу (so'm)", returnRate: 'Процент возвратов (%)', monthlyUnits: 'Продажи в месяц (шт.)',
      category: 'Категория', commissionSuffix: 'комиссия',
      uzumCommission: 'Комиссия Uzum:',
      enterToSee: 'Чтобы увидеть результат', enterPriceCost: 'введите цену и себестоимость',
      realityCheck: 'Reality Check — расчёт за месяц',
      youThink: 'Прибыль, которую вы ожидали', yourReal: 'Ваша реальная прибыль',
      uzumTook: 'Uzum + расходы забрали',
      kept: 'Осталось:', gone: 'Ушло:',
      breakdownTitle: 'Распределение расходов на 1 единицу товара:',
      bdCommission: 'Комиссия Uzum', bdCost: 'Себестоимость', bdLogistics: 'Логистика',
      bdReturnLoss: 'Потери от возвратов', bdAd: 'Реклама (шт.)', netProfitUnit: 'Чистая прибыль (шт.)',
      margin: 'Маржа', roi: 'ROI', drr: 'ДРР', breakeven: 'Точка безубыточности',
      warnLossPre: 'При текущей цене вы теряете', warnLossStrong: "so'm",
      warnLossMid: 'убытка в месяц. Поднимите цену минимум до', warnLossEnd: "so'm.",
      warnMarginPre: 'Маржа', warnMarginPost: '— слишком низкая. Нужно поднять цену или снизить себестоимость. Рекомендуемый минимум: 20%.',
      warnDrrPre: 'ДРР', warnDrrPost: '— расход на рекламу слишком высокий. Оптимально: 10–20%.',
      categories: ['Электроника', 'Компьютерная техника', 'Телефоны и гаджеты', 'Кроссовки', 'Спорт', 'Часы', 'Дом и сад', 'Одежда (мужская)', 'Одежда (женская)', 'Одежда (детская)', 'Красота и уход', 'Здоровье и медицина', 'Продукты питания', 'Игрушки', 'Автомобильные товары', 'Другое'],
    },
    settings: {
      title: 'Настройки', badge: 'Ваши данные', subtitle: 'Интеграции маркетплейсов',
      connected: 'Подключено', notConnected: 'Не подключено',
      apiToken: 'API Token', oauthToken: 'OAuth Token', campaignId: 'Campaign ID',
      tokenPlaceholderHas: '••••••••  (введите для обновления)', tokenPlaceholder: 'Введите токен…',
      oauthPlaceholder: 'Введите OAuth токен…', campaignPlaceholder: 'Campaign ID (например: 12345678)',
      uzumHint1: 'Настройки', uzumHint2: 'API-интеграция',
      yandexHint: 'OAuth токен и Campaign ID',
      save: 'Сохранить', sync: 'Синхронизировать', syncing: 'Синхронизация…',
      lastSyncPre: 'Последняя синхр.:', notSynced: 'Ещё не синхронизировано',
      saveTokenFirst: 'Сначала сохраните токен', saveTokenCampaignFirst: 'Сначала сохраните токен и Campaign ID',
      shopCreated: 'Магазин создан!', saved: 'Сохранено!', err: 'Ошибка',
      serverErr: 'Ошибка при соединении с сервером',
      syncResult1: 'товаров,', syncResult2: 'заказов обновлено.',
      syncAds: 'Синхр. рекламу', syncingAds: 'Синхронизирую рекламу…',
      adsSynced: 'записей рекламной статистики обновлено.',
      wbHint: 'Личный кабинет → Профиль → Доступ к API → Создать токен',
      extToken: 'Токен расширения', extTokenSub: 'Для расширения Chrome',
      currentToken: 'Текущий токен', copy: 'Копировать', copied: 'Скопировано!', copyTitle: 'Копировать',
      extInstrPre: 'Вставьте этот токен в поле', extInstrStrong: 'расширение Chrome → Options → Daromadchi token', extInstrPost: '',
      refresh: 'Обновить', refreshing: 'Обновление…',
      pwMin6: 'Должно быть не менее 6 символов', pwMismatch: 'Пароли не совпадают',
      pwChanged: 'Пароль успешно изменён!',
      pwSetNew: 'Установить новый пароль', pwSetNewDesc: 'Введите новый пароль не менее 6 символов',
      pwNew: 'Новый пароль', pwConfirm: 'Подтвердите пароль',
      pwSaving: 'Сохранение...', pwSave: 'Сохранить пароль',
      uzumAdsComing: 'Uzum Ads API пока недоступен — скоро будет добавлен.',
      yandexAdsComing: 'Статистика рекламы Yandex Market — скоро будет добавлена.',
    },
    sync: {
      title: 'Статус синхронизации',
      subtitle: 'Информация о последней синхронизации по маркетплейсам',
      connected: 'Подключён', notConnected: 'Не подключён',
      lastSync: 'Последняя синхр.:', notSynced: 'Ещё не синхронизировано',
      products: 'товаров', orders: 'заказов',
      syncNow: 'Синхронизировать', syncing: 'Синхронизирую…',
      syncAll: 'Синхронизировать всё',
      noShops: 'Нет подключённых магазинов',
      noShopsDesc: 'Перейдите в Настройки и подключите API-токен маркетплейса.',
      errorSync: 'Ошибка синхронизации',
      adsSync: 'Синхронизировать рекламу',
      adsSyncing: 'Синхронизирую рекламу…',
      adsNotAvailable: 'Ads API пока недоступен',
    },
    account: {
      title: 'Профиль', subtitle: 'Информация об аккаунте и тарифный план',
      defaultUser: 'Пользователь', joined: 'Зарегистрирован:',
      planTitle: 'Тарифный план', expires: 'Действует до:',
      planFree: 'Бесплатный', planPro: 'Pro', planProPlus: 'Pro+',
      freeDesc: '1 магазин · история 7 дней', proDesc: '3 магазина · Неограниченная история',
      proPlusDesc: '5 магазинов · Неограниченная история · Приоритетная поддержка',
      upgradePro: 'Перейти на Pro →',
      security: 'Безопасность', password: 'Пароль', passwordDesc: 'Измените ваш пароль', change: 'Изменить',
    },
    market: {
      title: 'Исследование рынка', badge: 'Публичные данные',
      subtitle: 'Цены конкурентов, заказы и трендовые товары',
      uzumNotice: "Используется публичный API Uzum.uz — токен не требуется. ",
      uzumYours: 'Товары в ваших категориях отмечаются.',
      uzumConnect: 'Подключите магазин, и ваши категории будут отмечаться автоматически.',
      connectLink: 'Подключить →',
      yandexNotice: 'Данные из каталога Yandex Market загружаются через ваш токен Partner API. Выберите категорию или найдите товар.',
      yandexNotConnected: 'Yandex Market не подключён',
      yandexNotConnectedDesc: 'Чтобы увидеть исследование рынка Yandex, подключите токен Partner API в Настройках.',
      yandexConnect: 'Подключить Yandex',
      minPrice: 'Мин. цена', avgPrice: 'Средняя цена', maxPrice: 'Макс. цена', totalOrders: 'Всего заказов',
      topProducts: 'Топ товаров — по заказам',
      product: 'Товар', price: 'Цена', orders: 'Заказы', rating: 'Рейтинг',
      yourCategory: 'Ваша категория',
      topModels: 'Yandex Market — топ моделей',
      model: 'Модель', priceRange: 'Диапазон цен', reviews: 'Отзывы', offers: 'Предложения',
      searchPlaceholder: 'Поиск по названию товара…', search: 'Найти',
      categories: 'Категории', loading: 'Загрузка…',
      resultsSuffix: 'результаты', productsCount: 'товаров', notFound: 'Данные не найдены',
      sortOrders: 'Заказы ↓', sortPriceAsc: 'Цена ↑', sortPriceDesc: 'Цена ↓', sortRating: 'Рейтинг ↓',
      sortOpinions: 'Отзывы ↓', sortPrice: 'Цена', sortQuality: 'Качество',
      estRevenue: 'Прогноз выручки', estRevenueNote: '* WB: отзывы × 15 × цена (отраслевая оценка)',
      sortRevenue: 'Выручка ↓', topRevenueProducts: 'Выручка конкурентов',
      revenueCol: 'Прогн. выручка', trending: 'Тренд',
    },
    abcxyz: {
      title: 'ABC-XYZ Анализ',
      subtitle: 'Классифицируйте товары по доходу и стабильности спроса',
      badge: 'Анализ запасов',
      classA: 'Класс A — основной доход (80%)',
      classB: 'Класс B — средний доход (15%)',
      classC: 'Класс C — низкий доход (5%)',
      classX: 'X — стабильный спрос (≥10 продаж)',
      classY: 'Y — умеренный спрос (1–9 продаж)',
      classZ: 'Z — нет спроса (0 продаж)',
      all: 'Все',
      product: 'Товар', revenue: 'Выручка', revenueShare: 'Доля', sold: 'Продано',
      abcClass: 'ABC', xyzClass: 'XYZ', combined: 'Класс',
      noData: 'Нет данных', noDataDesc: 'Синхронизируйте магазин, чтобы увидеть анализ товаров.',
      goSettings: 'Перейти в настройки',
      interpretation: 'Интерпретация',
      axDesc: 'AX — самые важные, стабильные товары. Всегда держите на складе.',
      azDesc: 'AZ — высокий доход, но непредсказуемый спрос. Управляйте осторожно.',
      cxDesc: 'CX — стабильный, но низкий доход. Пересмотрите ассортимент.',
      czDesc: 'CZ — наименьший приоритет. Рассмотрите исключение из ассортимента.',
    },
    advertising: {
      kpiSpend: 'Общий расход', kpiImpressions: 'Показы', kpiClicks: 'Клики',
      kpiOrders: 'Заказы', kpiRevenue: 'Выручка', kpiDrr: 'Средний ДРР',
      tabAll: 'Все',
      colCampaign: 'Кампания', colType: 'Тип', colStatus: 'Статус', colSpend: 'Расход',
      colImpressions: 'Показы', colClicks: 'Клики', colCtr: 'CTR',
      colOrders: 'Заказы', colRevenue: 'Выручка', colDrr: 'ДРР',
      statusActive: 'Активна', statusPaused: 'Приостановлена', statusEnded: 'Завершена',
      legendNoSale: 'Расход без продаж',
      myPrice: 'Моя цена', minComp: 'Мин. конкурент',
      pageTitle: 'Реклама', pageSubtitle: 'Аналитика рекламных кампаний CPC и CPO',
      noData: 'Нет данных по рекламе', noDataDesc: 'Синхронизируйте магазин для отображения рекламных данных. Вы также можете управлять кампаниями напрямую в кабинетах продавца:',
      goUzum: 'Перейти в кабинет Uzum', goWb: 'Перейти в кабинет Wildberries', goYandex: 'Перейти в кабинет Яндекс.Маркет',
    },
    reviews: {
      kpiTotal: 'Всего отзывов', kpiAvgRating: 'Средний рейтинг',
      kpiUnanswered: 'Без ответа', kpiNegative: 'Негативные',
      tabAll: 'Все', tabUnanswered: 'Без ответа', tabNegative: 'Негативные', tabPositive: 'Позитивные',
      searchPlaceholder: 'Поиск...',
      sentPositive: 'Позитивный', sentNegative: 'Негативный', sentNeutral: 'Нейтральный',
      needReply: 'Нужен ответ', replied: 'Ответ дан',
      replyBtn: 'Ответить', yourReply: 'Ваш ответ:', replyLabel: 'Напишите ответ:',
      replyPlaceholder: 'Напишите ответ покупателю...', replySend: 'Отправить', replyCancel: 'Отмена',
      notFound: 'Отзывы не найдены',
    },
    payouts: {
      kpiTotalPaid: 'Всего выплачено', kpiPending: 'Ожидает', kpiAvg: 'Средняя выплата',
      perPeriod: 'за период', periods: 'периодов',
      statusPaid: 'Выплачено', statusProcessing: 'В обработке', statusPending: 'Ожидает',
      segCommission: 'Комиссия', segDelivery: 'Доставка', segReturns: 'Возвраты',
      segAd: 'Реклама', segAcquiring: 'Эквайринг', segTax: 'Налог', segOther: 'Прочее',
      deductionsTitle: 'Детализация удержаний', totalDeductions: 'Итого удержания',
      colPeriod: 'Период', colOrders: 'Заказы', colGross: 'Брутто',
      colCommission: 'Комиссия', colDelivery: 'Доставка', colReturns: 'Возвраты',
      colAd: 'Реклама', colTax: 'Налог', colNet: 'Чистая выплата', colStatus: 'Статус',
    },
    seasonality: {
      insightBest: 'Лучший месяц', insightLow: 'Худший месяц',
      insightGrowth: 'Рост', insightCategory: 'Категория',
      insightBestSub: 'Запаситесь больше', insightLowSub: 'Сократите запасы',
      insightGrowthSub: 'Годовой тренд',
      chartSubtitle: 'Выручка за 12 месяцев', growthLabel: 'рост',
      legendPeak: 'Пиковый месяц', legendLow: 'Минимальный месяц',
      colMonth: 'Месяц', colRevenue: 'Выручка', colOrders: 'Заказы',
      colAvgCheck: 'Средний чек', colActivity: 'Активность',
      tagBest: 'Лучший', tagLow: 'Худший',
      recTitle: 'Рекомендация',
      recPeak1: '— самые высокие продажи. Запаситесь за', recPeak2: '1–2 месяца', recPeak3: 'до этого месяца.',
      recLow1: '— низкие продажи, снизьте расходы на рекламу в этот период.',
      tooltipRevenue: 'Выручка:', tooltipOrders: 'Заказы:', tooltipAvgCheck: 'Средний чек:',
    },
    stockAlerts: {
      kpiTotal: 'Всего уведомлений', kpiCritical: 'Критические (≤ 3 дня)', kpiWarning: 'Предупреждения (≤ 7 дней)',
      stockHeader: 'Состояние склада',
      settingsTitle: 'Настройки уведомлений', settingsThreshold: 'Критический порог остатков (шт.)',
      savingBtn: 'Сохранение…', savedBtn: 'Сохранено ✓', saveBtn: 'Сохранить',
      telegramHint: 'Для создания бота Telegram обратитесь к @BotFather',
      colProduct: 'Товар', colSku: 'SKU', colStock: 'Остаток',
      colThreshold: 'Порог', colDaysLeft: 'Дней осталось',
      colDailyStock: 'Ежедн. продажи', colStatus: 'Статус',
      statusCritical: 'Критический', statusWarning: 'Предупреждение', statusWatching: 'Наблюдение',
      emptyTitle: 'Все товары в норме',
      emptyDesc: 'Нет товаров, достигших критического уровня остатков',
      daysSuffix: 'дн.', perDay: '/день', units: 'шт.',
    },
    priceTracking: {
      kpiProducts: 'Отслеживаемые товары', kpiLowest: 'Минимальная цена',
      kpiHighest: 'Высокая / Самая высокая', kpiAvgGap: 'Средняя разница цен',
      kpiProductSub: 'товаров',
      tableTitle: 'Цены конкурентов',
      tabAll: 'Все', tabLowest: 'Мин. цена', tabCompetitive: 'Конкурентная', tabHigh: 'Дорогая',
      colProduct: 'Товар', colMyPrice: 'Моя цена', colMinComp: 'Мин. конкурент',
      colAvgMarket: 'Ср. рынок', colGap: 'Разница', colPosition: 'Позиция',
      colCompetitors: 'Конкуренты', colLastCheck: 'Последняя проверка',
      posLowest: 'Самая низкая', posCompetitive: 'Конкурентная', posHigh: 'Дороже', posHighest: 'Самая дорогая',
      myPrice: 'Моя цена', minComp: 'Мин. конкурент',
      emptyMsg: 'Товары по этому фильтру не найдены',
      infoText: 'Данные обновляются каждые 6 часов. Реальные цены синхронизируются через API Uzum.',
      priceDynamics: 'Динамика цен',
    },
    dataState: {
      statusReady: 'Готово', statusDegraded: 'Деградация', statusError: 'Ошибка', statusPending: 'Ожидает',
      clickToSelect: 'Нажмите для выбора',
      selectedDays: 'дней выбрано', resyncBtn: 'Повторить загрузку', cancelBtn: 'Отмена',
      last30Days: 'Последние 30 дней',
      colDate: 'Дата', colStatus: 'Статус', colProducts: 'Товары', colRevenue: 'Выручка', colError: 'Ошибка',
      legendClick: 'Нажмите на день для выбора → появится кнопка «Повторить загрузку»',
    },
    referral: {
      howTitle: 'Как это работает?',
      step1: 'Скопируйте вашу реферальную ссылку',
      step2: 'Друг регистрируется по ссылке',
      step3: 'Получайте 50 000 сум за каждого активного друга',
      yourLink: 'Ваша реферальная ссылка',
      yourCode: '— ваш код',
      copyBtn: 'Скопировать', copiedBtn: 'Скопировано!',
      kpiTotal: 'Всего приглашено', kpiActive: 'Активных',
      kpiPending: 'Ожидают', kpiReward: 'Итого вознаграждение',
      tableTitle: 'Приглашённые пользователи',
      colNum: '#', colDate: 'Дата', colStatus: 'Статус', colActivated: 'Активирован', colReward: 'Вознаграждение',
      statusActive: 'Активен', statusPaid: 'Выплачено', statusPending: 'Ожидает',
      emptyTitle: 'Ещё никого не приглашено',
      emptyDesc: 'Поделитесь ссылкой выше и получайте вознаграждение',
    },
    keywords: {
      title: 'Поисковые фразы',
      subtitle: 'По каким ключевым словам находят ваши товары, сколько показов и кликов они получают. Отслеживайте CTR и среднюю позицию.',
      demoNotice: 'Демо-режим.',
      demoDesc: 'Данные ниже являются примерными — это не ваши реальные товары. Функция аналитики поиска Uzum Market в разработке.',
      kpiImpressions: 'Всего показов', kpiClicks: 'Всего кликов',
      kpiCtr: 'Средний CTR', kpiGrowing: 'Растущих',
      kpiGrowingUnit: '',
      searchPlaceholder: 'Товар или ключевое слово...',
      tabAll: 'Все', tabGrowing: 'Растущие', tabDeclining: 'Падающие',
      colProduct: 'Название товара', colKeywords: 'Ключевые слова',
      colImpressions: 'Показы', colClicks: 'Клики',
      colCtr: 'CTR', colPosition: 'Позиция', colTrend: 'Тренд',
      notFound: 'Результаты не найдены',
      showing: 'товаров показано',
    },
  },
} satisfies Record<Lang, unknown>
