import type { Lang } from './i18n'

type Tr = Record<Lang, string>

function tr(ru: string, uz: string, en: string): Tr {
  return { ru, uz, en }
}

export const T = {
  nav: {
    howItWorks: tr('Как работает', 'Qanday ishlaydi', 'How it works'),
    pricing: tr('Тарифы', 'Tariflar', 'Pricing'),
    extension: tr('Расширение', 'Kengaytma', 'Extension'),
    help: tr('Помощь', 'Yordam', 'Help'),
  },

  mockup: {
    revenue: tr('Выручка', 'Daromad', 'Revenue'),
    orders: tr('Заказы', 'Buyurtmalar', 'Orders'),
    expenses: tr('Расход', 'Xarajat', 'Expenses'),
    profit: tr('Прибыль', 'Foyda', 'Profit'),
    sum: tr('сум', "so'm", 'sum'),
    all: tr('Все', 'Barchasi', 'All'),
    dateRange: tr('17 мар — 30 мар 2026', '17-mar — 30-mar 2026', 'Mar 17 — Mar 30, 2026'),
    dailyRevenue: tr('Выручка по дням', 'Kunlik daromad', 'Daily revenue'),
    platforms: tr('Площадки', 'Maydonchalar', 'Platforms'),
    product: tr('Товар', 'Mahsulot', 'Product'),
    sku: tr('Артикул', 'Artikul', 'SKU'),
    revenueSum: tr('Выручка, сум', "Daromad, so'm", 'Revenue, sum'),
    drrPct: tr('ДРР%', 'DRR%', 'DRR%'),
    status: tr('Статус', 'Holat', 'Status'),
    winterJacket: tr('Куртка зимняя мужская', 'Erkaklar qishki kurtkasi', "Men's winter jacket"),
    nikeAir: tr('Кроссовки Nike Air', 'Nike Air krossovka', 'Nike Air sneakers'),
    hikingBackpack: tr('Рюкзак туристический', 'Turist ryuksaki', 'Hiking backpack'),
    sonyHeadphones: tr('Наушники Sony WH-1000', 'Sony WH-1000 quloqchin', 'Sony WH-1000 headphones'),
    ok: tr('Норма', 'Normal', 'OK'),
    low: tr('Мало', 'Kam', 'Low'),
  },

  hero: {
    headingLine1: tr('Управляйте продажами на трёх маркетплейсах', "Uchta marketpleys sotuvlaringizni bitta joydan boshqaring", 'Manage your sales across three marketplaces'),
    headingLine2: tr('из одной панели', '', 'from one dashboard'),
    subtitle: tr(
      'Выручка, ДРР, остатки и юнит-экономика по Uzum, Wildberries и Yandex Market — обновление каждые 15 минут, без ручного ввода',
      "Uzum, Wildberries va Yandex Market bo'yicha daromad, DRR, qoldiqlar va birlik-iqtisod — har 15 daqiqada yangilanadi, qo'lda kiritishsiz",
      'Revenue, DRR, stock and unit economics across Uzum, Wildberries and Yandex Market — updated every 15 minutes, no manual entry',
    ),
    startFree: tr('Начать бесплатно', 'Bepul boshlash', 'Start for free'),
    howItWorks: tr('Как это работает', 'Qanday ishlaydi', 'How it works'),
  },

  comparison: {
    title: tr(
      'Сейчас вы видите только половину данных',
      "Hozir siz ma'lumotlarning yarmini ko'ryapsiz",
      "You're only seeing half the data",
    ),
    accent: tr('половину данных', 'yarmini', 'half the data'),
    sub: tr(
      'Три отдельных кабинета не дают общей картины — приходится переключаться и складывать цифры вручную',
      "Uchta alohida kabinet umumiy rasmni bermaydi — raqamlarni qo'lda hisoblashga to'g'ri keladi",
      'Three separate dashboards give no unified view — you switch tabs and add up numbers by hand',
    ),
    row1: tr('Выручка по всем площадкам', "Barcha saytlar bo'yicha daromad", 'Revenue across all platforms'),
    row2: tr('ДРР в реальном времени', 'Real vaqt DRR', 'Real-time ad spend ratio'),
    row3: tr('Остатки по складам', 'Ombor qoldiqlari', 'Stock by warehouse'),
    row4: tr('Юнит-экономика', 'Birlik-iqtisod', 'Unit economics'),
    row5: tr('Уведомления в Telegram', 'Telegram bildirishnomalari', 'Telegram notifications'),
    row6: tr('Экспорт в Excel', 'Excel ga eksport', 'Excel export'),
    separateDashboards: tr('3 кабинета по отдельности', '3 ta alohida kabinet', '3 separate dashboards'),
    tryFree: tr('Попробовать бесплатно', "Bepul sinab ko'ring", 'Try for free'),
  },

  marquee: {
    salesAnalytics: tr('Аналитика продаж', 'Savdo tahlili', 'Sales analytics'),
    unitEconomics: tr('Юнит-экономика', 'Birlik iqtisodiyoti', 'Unit economics'),
    drrControl: tr('ДРР контроль', 'DRR nazorat', 'DRR control'),
    excelExport: tr('Excel экспорт', 'Excel eksport', 'Excel export'),
    labelLine1: tr('ИНТЕГРИРОВАННЫЕ', 'INTEGRATSIYA QILINGAN', 'INTEGRATED'),
    labelLine2: tr('ПЛОЩАДКИ И ФУНКЦИИ', 'BOZORLAR VA FUNKSIYALAR', 'MARKETS & FEATURES'),
  },

  features: {
    revenue: tr('Выручка', 'Tushum', 'Revenue'),
    profit: tr('Прибыль', 'Foyda', 'Profit'),
    orders: tr('Заказы', 'Buyurtmalar', 'Orders'),
    stock: tr('Остатки', 'Qoldiq', 'Stock'),
    dailyRevenue: tr('Дневная выручка', 'Kunlik tushum', 'Daily revenue'),
    categories: tr('Категории', 'Kategoriyalar', 'Categories'),
    recentOrders: tr('Последние заказы', "So'nggi buyurtmalar", 'Recent Orders'),
    status: tr('Статус', 'Holat', 'Status'),
    delivered: tr('Доставлен', 'Yetkazildi', 'Delivered'),
    processing: tr('В обработке', 'Jarayonda', 'Processing'),
    badge: tr('АНАЛИТИКА В РЕАЛЬНОМ ВРЕМЕНИ', 'REAL-TIME ANALITIKA', 'REAL-TIME ANALYTICS'),
    headingLine1: tr('Продажи и аналитика —', 'Savdo va analitika —', 'Sales & Analytics —'),
    headingAccentLine: tr('всё в одном месте', 'hammasi bir joyda', 'all in one place'),
    description: tr(
      'ДРР, остатки, цены и юнит-экономика. Управляйте продажами за 5 минут в день.',
      "DRR, qoldiq, narx va birlik iqtisodiyoti. Savdoni kuniga 5 daqiqada boshqaring.",
      'DRR, stock, pricing and unit economics. Manage your sales in 5 minutes a day.',
    ),
    feature1Title: tr('Выручка и прибыль в реальном времени', 'Real-time daromad va foyda', 'Real-time revenue & profit'),
    feature1Desc: tr(
      'Следите за KPI по каждому маркетплейсу и временному периоду',
      'Har bir marketpleysning KPIlarini kuzating',
      'Track KPIs per marketplace and time period',
    ),
    feature2Title: tr('ДРР и рентабельность по каждому товару', 'Har bir mahsulot uchun DRR va rentabellik', 'DRR & profitability per product'),
    feature2Desc: tr(
      'Найдите убыточные позиции и скорректируйте ставки рекламы',
      "Zarar keltiruvchi pozitsiyalarni toping",
      'Find losing products and adjust ad bids',
    ),
    feature3Title: tr('Уведомления в Telegram каждые 15 минут', 'Har 15 daqiqada Telegram bildirishnomalari', 'Telegram alerts every 15 minutes'),
    feature3Desc: tr(
      'Критические алерты по остаткам и превышению ДРР',
      "Qoldiqlar va DRR oshishi haqida ogohlantirishlar",
      'Critical alerts for stock and DRR spikes',
    ),
    startFree3Days: tr('Начать бесплатно 3 дня →', '3 kun bepul boshlash →', 'Start free 3 days →'),
    explorePlatform: tr('Изучить платформу →', "Platformani o'rganish →", 'Explore platform →'),
  },

  howItWorks: {
    title: tr("Настройте магазин за 5 минут", "Do'koningizni 5 daqiqada sozlang", 'Set up your store in 5 minutes'),
    accent: tr('за 5 минут', '5 daqiqada', 'in 5 minutes'),
    sub: tr('Три шага до полной аналитики', "To'liq tahlilgacha uch qadam", 'Three steps to full analytics'),
    step1Title: tr('Регистрация', "Ro'yxatdan o'tish", 'Register'),
    step1Desc: tr(
      'Зарегистрируйтесь в системе и начните пользоваться нашей платформой',
      "Tizimga ro'yxatdan o'ting va platformamizdan foydalanishni boshlang",
      'Sign up in the system and start using our platform',
    ),
    password: tr('Пароль', 'Parol', 'Password'),
    signUp: tr('Зарегистрироваться', "Ro'yxatdan o'tish", 'Sign up'),
    step2Title: tr('Подключите магазин', "Do'koningizni ulang", 'Connect your store'),
    step2Desc: tr(
      'Вставьте API-ключ из кабинета Uzum, WB или Яндекс — получите доступ к данным магазина, платформа работает в режиме «только чтение»',
      "Uzum, WB yoki Yandex kabinetidan API kalitini kiriting — do'kon ma'lumotlariga kirish oling, platforma «faqat o'qish» rejimida ishlaydi",
      'Paste API key from Uzum, WB or Yandex — and access to your store\'s data, our platform works in "read only" mode.',
    ),
    yourStores: tr('Ваши магазины', "Do'konlaringiz", 'Your stores'),
    step3Title: tr('Данные готовы', "Ma'lumotlar tayyor", 'Data is ready'),
    step3Desc: tr(
      'Данные синхронизируются автоматически — вся история продаж с момента подключения, без ручного ввода',
      "Ma'lumotlar avtomatik sinxronlanadi — do'koningizni ulagan paytdan boshlab barcha sotuv tarixi ko'rinadi",
      'Data syncs automatically — full sales history from the moment you connect, no manual entry needed',
    ),
    dailyRevenue: tr('Выручка по дням', 'Kunlik daromad', 'Daily revenue'),
    connectFree: tr('Подключить бесплатно', 'Bepul ulash', 'Connect for free'),
  },

  bento: {
    title: tr("Все данные маркетплейсов в одном дашборде", "Barcha marketplace ma'lumotlari bitta dashboardda", 'All your marketplace data in one dashboard'),
    accent: tr('одном дашборде', 'bitta dashboardda', 'one dashboard'),
    sub: tr(
      'Аналитика продаж, контроль остатков и управление финансами — в реальном времени по всем трём площадкам',
      "Sotuv tahlili, zaxira nazorati va moliyaviy boshqaruv — uchala maydoncha bo'yicha real vaqtda",
      'Real-time profit tracking, DRR control, and inventory management across all three marketplaces',
    ),
    revenue: tr('Выручка', 'Daromad', 'Revenue'),
    orders: tr('Заказы', 'Buyurtmalar', 'Orders'),
    drr: tr('ДРР', 'DRR', 'DRR'),
    profit: tr('Прибыль', 'Foyda', 'Profit'),
    thisMonth: tr('за месяц', 'oyda', 'this month'),
    analyticsLabel: tr('АНАЛИТИКА', 'TAHLIL', 'ANALYTICS'),
    analyticsTitle: tr('Аналитика маркетплейсов', 'Analitika markazi', 'Marketplace analytics'),
    analyticsDesc: tr(
      'Uzum, Wildberries и Yandex Market — обновление каждые 15 минут',
      'Uzum, Wildberries va Yandex Market — har 15 daqiqada yangilanadi',
      'Uzum, Wildberries & Yandex Market — updates every 15 min',
    ),
    dailyRevenue: tr('Выручка по дням', 'Kunlik daromad', 'Daily revenue'),
    inventoryLabel: tr('ЗАПАСЫ', 'ZAXIRA', 'INVENTORY'),
    inventoryTitle: tr('Контроль остатков', 'Zaxira nazorati', 'Stock control'),
    inventoryDesc: tr(
      'Алерты когда товар заканчивается, по каждому складу',
      "Har bir ombor bo'yicha mahsulot tugayotganda ogohlantirish",
      'Alerts when stock runs low, per warehouse',
    ),
    jacket: tr('Куртка', 'Qishki kurtka', 'Jacket'),
    sneakers: tr('Кроссовки', 'Krossovka', 'Sneakers'),
    backpack: tr('Рюкзак', 'Ryuksak', 'Backpack'),
    pcs: tr('шт', 'ta', 'pcs'),
    financeLabel: tr('ФИНАНСЫ', 'MOLIYA', 'FINANCE'),
    financeTitle: tr('Отчёт о прибыли', 'Foyda hisobi', 'Profit report'),
    financeDesc: tr(
      'Полная структура доходов и расходов по каждому каналу',
      "Har bir kanal bo'yicha to'liq daromad va xarajatlar tuzilmasi",
      'Full revenue and cost breakdown per channel',
    ),
    revenueRow: tr('Выручка', 'Daromad', 'Revenue'),
    commission: tr('Комиссия', 'Komissiya', 'Commission'),
    delivery: tr('Доставка', 'Yetkazib berish', 'Delivery'),
    profitRow: tr('Прибыль', 'Foyda', 'Profit'),
  },

  extension: {
    title: tr('Расширение для браузера', 'Brauzer kengaytmasi', 'Browser extension'),
    accent: tr('Расширение', 'kengaytmasi', 'extension'),
    sub: tr(
      'Рассчитайте маржу, комиссию и прибыль прямо на странице товара — без переключения вкладок',
      "Mahsulot sahifasida marjani, komissiyani va foydani hisoblang — yorliqlarni almashtirmasdan",
      'Calculate margin, commission and profit right on the product page — no tab switching',
    ),
    uzumHeadline: tr(
      'Мгновенный расчёт маржи и FBO/FBS на странице товара',
      'Mahsulot sahifasida FBO/FBS marja hisoblash',
      'Instant margin & FBO/FBS calc on any product page',
    ),
    uzumPoint1: tr('Комиссия маркетплейса и эквайринг', 'Marketplace va ekvayring komissiyasi', 'Marketplace fee & acquiring'),
    uzumPoint2: tr('Стоимость хранения, доставки и возвратов', 'Saqlash, yetkazib berish va qaytarish xarajatlari', 'Storage, delivery & return costs'),
    uzumPoint3: tr('Чистая прибыль и маржа в одно нажатие', 'Bir bosishda sof foyda va marja', 'Net profit & margin in one click'),
    wbHeadline: tr(
      'Тарифы FBW и FBS с учётом категории товара',
      'Mahsulot toifasiga qarab FBW va FBS tariflari',
      'FBW & FBS rates by product category',
    ),
    wbPoint1: tr('Стоимость хранения на складе WB', 'WB omborida saqlash narxi', 'WB warehouse storage cost'),
    wbPoint2: tr('Расходы на возвраты и логистику', 'Qaytarish va logistika xarajatlari', 'Return & logistics expenses'),
    wbPoint3: tr('ДРР и рентабельность по каждому SKU', "Har bir SKU bo'yicha DRR va rentabellik", 'DRR & profitability per SKU'),
    ymHeadline: tr(
      'Расчёт DBS и FBY с учётом всех комиссий',
      'Barcha komissiyalar hisobga olingan DBS va FBY hisoblash',
      'DBS & FBY calculation including all commissions',
    ),
    ymPoint1: tr('Комиссии категорий и программ лояльности', 'Kategoriya va sodiqlik dasturlari komissiyalari', 'Category & loyalty program commissions'),
    ymPoint2: tr('Стоимость доставки до покупателя', 'Xaridorgacha yetkazib berish narxi', 'Delivery cost to customer'),
    ymPoint3: tr('Сравнение DBS vs FBY по чистой прибыли', "Sof foyda bo'yicha DBS vs FBY taqqoslash", 'Profit comparison DBS vs FBY'),
    freeName: tr('Бесплатно', 'Bepul', 'Free'),
    freeHeadline: tr(
      'Устанавливается из Chrome Web Store за несколько секунд',
      "Chrome Web Store dan bir necha soniyada o'rnatiladi",
      'Install from Chrome Web Store in seconds',
    ),
    freePoint1: tr('Совместим с Chrome, Edge и Brave', 'Chrome, Edge va Brave bilan mos', 'Works on Chrome, Edge & Brave'),
    freePoint2: tr('Требуется аккаунт Daromadchi для полного доступа', "To'liq kirish uchun Daromadchi hisobi talab etiladi", 'Daromadchi account required for full access'),
    freePoint3: tr('0 сум, навсегда бесплатно', "0 so'm, doimo bepul", '0 sum, free forever'),
    installBtn: tr('Установить расширение', "Kengaytmani o'rnatish", 'Install extension'),
    browserNote: tr('Chrome · Edge · Brave — бесплатно', 'Chrome · Edge · Brave — bepul', 'Chrome · Edge · Brave — free'),
  },

  pricing: {
    label: tr('ТАРИФЫ', 'TARIFLAR', 'PRICING'),
    title: tr('Тариф для вашего бизнеса', 'Biznesingizga mos tarif', 'A plan for your business'),
    sub: tr(
      'Начните бесплатно, масштабируйтесь по мере роста',
      "Bepul boshlang, o'sish bilan kengaytiring",
      'Start free, scale as you grow',
    ),
    freeName: tr('Бесплатно', 'Bepul', 'Free'),
    freeSub: tr('навсегда', 'abadiy', 'forever'),
    freeFeature1: tr('Демо-данные', "Demo ma'lumotlar", 'Demo data'),
    freeFeature2: tr('1 магазин', "1 do'kon", '1 store'),
    freeFeature3: tr('6 страниц аналитики', '6 tahlil sahifasi', '6 analytics pages'),
    freeCta: tr('Начать бесплатно', 'Bepul boshlash', 'Start free'),
    proBadge: tr('Популярный', 'Ommabop', 'Popular'),
    proSub: tr('сум / месяц', "so'm / oy", 'sum / month'),
    proFeature1: tr('До 3 магазинов', "3 ta do'kongacha", 'Up to 3 stores'),
    proFeature2: tr('Вся аналитика', 'Barcha tahlillar', 'All analytics'),
    proFeature3: tr('Автосинхронизация', 'Avto-sinxronizatsiya', 'Auto-sync'),
    proFeature4: tr('P&L отчёт', 'P&L hisobot', 'P&L report'),
    proFeature5: tr('Email-уведомления', 'Email ogohlantirishlar', 'Email notifications'),
    proCta: tr('Попробовать Pro', "Pro ni sinab ko'rish", 'Try Pro'),
    proPlusSub: tr('сум / месяц', "so'm / oy", 'sum / month'),
    proPlusFeature1: tr('5+ магазинов', "5+ do'konlar", '5+ stores'),
    proPlusFeature2: tr('Всё из Pro', 'Barcha Pro imkoniyatlar', 'Everything in Pro'),
    proPlusFeature3: tr('API-доступ', 'API kirish', 'API access'),
    proPlusFeature4: tr('Приоритетная поддержка', 'Ustuvor yordam', 'Priority support'),
    proPlusCta: tr('Подключить Pro+', 'Pro+ ulash', 'Get Pro+'),
  },

  resources: {
    title: tr('Помощь и интеграции', 'Yordam va integratsiyalar', 'Help & integrations'),
    accent: tr('интеграции', 'integratsiyalar', 'integrations'),
    sub: tr(
      'Документация, Telegram-сообщество и подключение площадок',
      "Hujjatlar, Telegram-hamjamiyat va maydonchalarni ulash",
      'Documentation, Telegram community and marketplace connections',
    ),
    helpTitle: tr('Справка', 'Yordam markazi', 'Help center'),
    helpDesc: tr(
      'Пошаговые руководства по настройке, формулам DRR и юнит-экономике — всё в одном месте',
      "Sozlash, DRR formulalari va birlik-iqtisod bo'yicha bosqichma-bosqich qo'llanmalar",
      'Step-by-step guides on setup, DRR formulas and unit economics — all in one place',
    ),
    helpItem1Title: tr('Быстрый старт за 5 минут', '5 daqiqada tez boshlash', 'Quick start in 5 min'),
    helpItem1Desc: tr('Пошаговое руководство', "Bosqichma-bosqich qo'llanma", 'Step-by-step guide'),
    helpItem2Title: tr('Как работает ДРР', 'DRR qanday ishlaydi', 'How DRR works'),
    helpItem2Desc: tr('Формула и примеры', 'Formula va misollar', 'Formula and examples'),
    helpItem3Title: tr('Настройка юнит-экономики', 'Birlik-iqtisodni sozlash', 'Setting up unit economics'),
    helpItem3Desc: tr('Укажите закупку и логистику', 'Xarid va logistikani kiriting', 'Enter purchase costs & logistics'),
    helpLink: tr('Все статьи →', 'Barcha maqolalar →', 'All articles →'),
    tgItem1Title: tr('Канал с обновлениями', 'Yangilanishlar kanali', 'Updates channel'),
    tgItem1Desc: tr('Новые функции и релизы', 'Yangi funksiyalar va relizlar', 'New features & releases'),
    tgItem2Title: tr('Чат поддержки', "Qo'llab-quvvatlash chati", 'Support chat'),
    tgItem2Desc: tr('Ответ в течение часа', 'Bir soat ichida javob', 'Reply within an hour'),
    tgItem3Title: tr('Сообщество продавцов', 'Sotuvchilar hamjamiyati', 'Sellers community'),
    tgItem3Desc: tr('Советы и кейсы', 'Maslahatlar va holatlar', 'Tips & case studies'),
    tgLink: tr('Открыть Telegram →', 'Telegramni ochish →', 'Open Telegram →'),
    integrationsTitle: tr('Интеграции', 'Integratsiyalar', 'Integrations'),
    intUzumDesc: tr('Подключение через API-ключ', 'API kalit orqali ulash', 'Connect via API key'),
    intWbDesc: tr('Подключение через токен WB', 'WB token orqali ulash', 'Connect via WB token'),
    intYmDesc: tr('OAuth-авторизация', 'OAuth-avtorizatsiya', 'OAuth authorisation'),
    intLink: tr('Инструкция по подключению →', "Ulash yo'riqnomasi →", 'Connection guide →'),
  },

  faq: {
    title: tr('Частые вопросы', "Tez-tez so'raladigan savollar", 'Frequently asked questions'),
    accent: tr('вопросы', 'savollar', 'questions'),
    q1: tr('Безопасно ли подключать API-ключ?', 'API kalitini ulash xavfsizmi?', 'Is it safe to connect my API key?'),
    a1: tr(
      'Да. Мы используем только Read Only ключи — мы можем читать данные из вашего магазина, но никогда не можем изменять цены, товары или заказы. Ключ хранится в зашифрованном виде.',
      "Ha. Biz faqat Read Only kalitlaridan foydalanamiz — biz do'kongingizdagi ma'lumotlarni o'qiy olamiz, lekin narxlar, mahsulotlar yoki buyurtmalarni hech qachon o'zgartira olmaymiz.",
      'Yes. We only use Read Only keys — we can read data from your store but can never modify prices, products or orders. The key is stored encrypted.',
    ),
    q2: tr(
      'Как быстро появляются данные после подключения?',
      "Ulanganidan keyin ma'lumotlar qanchalik tez paydo bo'ladi?",
      'How quickly does data appear after connecting?',
    ),
    a2: tr(
      'Первая синхронизация занимает до 5 минут и подтягивает историю за последние 7 дней. Далее данные обновляются автоматически каждые 15 минут для заказов и каждые 4 часа для статистики.',
      "Birinchi sinxronizatsiya 5 daqiqagacha davom etadi va so'nggi 7 kunlik tarixni tortib oladi. Keyin buyurtmalar uchun har 15 daqiqada, statistika uchun har 4 soatda avtomatik yangilanadi.",
      'First sync takes up to 5 minutes and pulls 7 days of history. After that, orders update every 15 minutes and statistics every 4 hours.',
    ),
    q3: tr(
      'Поддерживаете ли все три маркетплейса?',
      "Uchala marketpleysni ham qo'llayapsizmi?",
      'Do you support all three marketplaces?',
    ),
    a3: tr(
      'Да — Uzum Market, Wildberries и Yandex Market полностью поддерживаются. Данные из всех трёх платформ объединяются в единую таблицу с разбивкой по площадкам.',
      "Ha — Uzum Market, Wildberries va Yandex Market to'liq qo'llaniladi.",
      'Yes — Uzum Market, Wildberries and Yandex Market are fully supported. Data from all three platforms is merged into one table with per-platform breakdown.',
    ),
    q4: tr('Как работает юнит-экономика?', 'Birlik-iqtisod qanday ishlaydi?', 'How does unit economics work?'),
    a4: tr(
      'Вы вводите закупочную цену, логистику и прочие расходы по каждому товару. Daromadchi автоматически рассчитывает маржу, ROI и минимальную цену продажи для безубыточности.',
      'Har bir mahsulot uchun xarid narxi, logistika va boshqa xarajatlarni kiritasiz. Daromadchi avtomatik ravishda marja, ROI va minimal sotish narxini hisoblaydi.',
      'You enter purchase price, logistics and other costs per product. Daromadchi automatically calculates margin, ROI and minimum break-even price.',
    ),
    q5: tr('Есть ли мобильная версия?', 'Mobil versiya bormi?', 'Is there a mobile version?'),
    a5: tr(
      'Веб-версия адаптирована для мобильных устройств и работает в любом браузере. Нативное мобильное приложение в дорожной карте на август 2026 года.',
      "Veb-versiya mobil qurilmalar uchun moslashtirilgan. Mahalliy mobil ilova avgust 2026 yo'l xaritasida.",
      'The web version is mobile-responsive and works in any browser. A native mobile app is on the roadmap for August 2026.',
    ),
    q6: tr("Можно ли попробовать перед оплатой?", "To'lovdan oldin sinab ko'rsa bo'ladimi?", 'Can I try before paying?'),
    a6: tr(
      'Да, есть бесплатный тариф без ограничения по времени: до 1 магазина, топ-50 товаров, ежедневные обновления. Для доступа ко всем функциям — Pro от 149 000 сум/мес.',
      "Ha, vaqt cheklovisiz bepul tarif mavjud: 1 do'kongacha, top-50 mahsulot, kunlik yangilanishlar.",
      "Yes, there's a free tier with no time limit: up to 1 store, top 50 products, daily updates. For all features — Pro from 149,000 sum/month.",
    ),
  },

  cta: {
    heading: tr(
      'Хотите увеличить продажи вместе с нами?',
      'Biz bilan savdolaringizni oshirmoqchimisiz?',
      'Ready to grow your sales with us?',
    ),
    thenLetsGo: tr('Тогда поехали', 'Unda kettik', "Then let's go"),
    subtext: tr(
      'Подключите магазин за несколько минут. Бесплатный тариф, без привязки карты',
      "Do'koningizni bir necha daqiqada ulang. Bepul tarif, karta bog'lanmaydi",
      'Connect your store in minutes. Free plan, no credit card required',
    ),
    ctaBtn: tr(
      'Устали терять деньги? Начните зарабатывать →',
      'Zarar emas — foyda. Bugunoq boshlang →',
      "Your profit is hiding — let's go find it →",
    ),
    badge1: tr('✓ 7 дней — только Pro и Pro+', '✓ 7 kun — faqat Pro va Pro+', '✓ 7 days — Pro & Pro+ only'),
    badge2: tr('✓ Без карты', '✓ Kartasiz', '✓ No card'),
    badge3: tr('✓ Быстрое подключение', '✓ Tez ulanish', '✓ Quick setup'),
    revenue: tr('Выручка', 'Daromad', 'Revenue'),
    revenueValue: tr('24.5M сум', "24.5M so'm", '24.5M sum'),
    orders: tr('Заказы', 'Buyurtmalar', 'Orders'),
    drr: tr('ДРР', 'DRR', 'DRR'),
    profit: tr('Прибыль', 'Foyda', 'Profit'),
    profitValue: tr('6.8M сум', "6.8M so'm", '6.8M sum'),
  },

  footer: {
    description: tr(
      'Аналитика Uzum, Wildberries и Yandex Market для продавцов из Узбекистана',
      "O'zbekistondagi sotuvchilar uchun Uzum, Wildberries va Yandex Market tahlili",
      'Analytics for Uzum, Wildberries and Yandex Market sellers in Uzbekistan',
    ),
    productHead: tr('Продукт', 'Mahsulot', 'Product'),
    signIn: tr('Войти', 'Kirish', 'Sign in'),
    register: tr('Регистрация', "Ro'yxatdan o'tish", 'Register'),
    pricing: tr('Тарифы', 'Tariflar', 'Pricing'),
    features: tr('Возможности', 'Imkoniyatlar', 'Features'),
    about: tr('О нас', 'Biz haqimizda', 'About'),
    marketplacesHead: tr('Маркетплейсы', 'Marketpleyslar', 'Marketplaces'),
    contactHead: tr('Контакты', 'Aloqa', 'Contact'),
    location: tr('г. Ташкент, Узбекистан', "Toshkent shahri, O'zbekiston", 'Tashkent, Uzbekistan'),
    privacy: tr('Конфиденциальность', 'Maxfiylik', 'Privacy'),
    terms: tr('Публичная оферта', 'Ommaviy oferta', 'Terms'),
    compliance: tr('Соответствие данных', 'Muvofiqlik', 'Compliance'),
  },

  mobileNav: {
    home: tr('Главная', 'Bosh sahifa', 'Home'),
    features: tr('Функции', 'Imkoniyatlar', 'Features'),
    pricing: tr('Тарифы', 'Tariflar', 'Pricing'),
    faq: tr('Вопросы', 'Savollar', 'FAQ'),
    profile: tr('Профиль', 'Profil', 'Profile'),
  },
} as const
