-- 043_suggested_product_groups.sql
-- Read-only "product group" suggestions (Feature A, Phase 1). Cross-marketplace
-- pairs that look like the same physical product, generated by
-- scripts/suggest-product-groups.ts for a human to approve. NEVER auto-merged;
-- on approval the API writes a product_group_merges row that computeStockGroups
-- already consumes. Pair keys are stored in canonical (sorted) order so a pair is
-- never suggested twice in both directions. Idempotent — safe to re-run.

CREATE TABLE IF NOT EXISTS suggested_product_groups (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  a_match_key  text NOT NULL,
  b_match_key  text NOT NULL,
  a_product_id uuid REFERENCES products(id) ON DELETE SET NULL,
  b_product_id uuid REFERENCES products(id) ON DELETE SET NULL,
  score        numeric(4,3) NOT NULL,
  tier         text NOT NULL,
  signals      jsonb,
  status       text NOT NULL DEFAULT 'pending',
  reviewed_at  timestamptz,
  created_at   timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS suggested_product_groups_pair_unique
  ON suggested_product_groups (user_id, a_match_key, b_match_key);
CREATE INDEX IF NOT EXISTS suggested_product_groups_user_status_idx
  ON suggested_product_groups (user_id, status);
