name: Deploy to VPS

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Hetzner VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
QyNTUxOQAAACBjtjrXF7qNb9+zFdFAWr4rEq8iRLAJrYBBdzuCAk8tGAAAAJiT4pKik+KS
ogAAAAtzc2gtZWQyNTUxOQAAACBjtjrXF7qNb9+zFdFAWr4rEq8iRLAJrYBBdzuCAk8tGA
AAAECXLPMEZyQVNBrJd8rhKttl9Tq512hjmGkBwJgN3ZX0tWO2OtcXuo1v37MV0UBavisS
ryJEsAmtgEF3O4ICTy0YAAAAFHJvb3RAZGFyb21hZGNoaS1wcm9kAQ== }}
          script: |
            cd /var/www/daromadchi
            bash deploy.sh
